### ISSUE TITLE
Start-LabConfiguration: Add ability to skip nodes

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#112]
Sometimes (like when debugging multiple VM configurations) it would be handy to be able to only deploy specific nodes (or exclude particular nodes). This is only really an issue when the VMs contain large custom resources (Exchange and XenDesktop etc).

In my use case, I have a lab configuration with both Exchange 2013 SP1 and Citrix XenDesktop 7.x in it. To deploy that the Exchange and/or XenApp nodes (expanding resource ISO into the VHDX) takes a long (longer than I'd like) time. If I'm just testing updates to the DC, it would be ideal to just deploy that.

**Comment by iainbrighton** [comment]
Oh - I could create two different configurations (psd1) files; one for testing and one for deployment, but where is the fun in that?!

**Comment by ryanspletzer** [comment]
This would be cool, right now I just comment out certain nodes I don't want from the psd1.

**Comment by iainbrighton** [comment]
@ryanspletzer I use the `Reset-LabVM` cmdlet to do this. For example:
```powershell
Reset-LabVM -Name EXCHANGE,XENAPP -ConfigurationData ~\Documents\Training\TrainingLab.psd1 -Path .\ -NoSnapshot -Credential $credential -Verbose | Start-VM
```
This will just (re)provision the `EXCHANGE` and `XENAPP` nodes in the configuration :wink:

**Comment by ryanspletzer** [comment]
Ah nice!

**Comment by iainbrighton** [comment]
Closing this one out, as I think that the Reset-LabVM "trick" solves the debugging problem. Deploying a lab should always deploy all nodes..
