### ISSUE TITLE
131.107.* IP's in Examples

### ISSUE THREAD

**Issue by ryanspletzer** [VirtualEngine/Lability#114]
I noticed these IP's in the Test Lab Guide examples when I was working with the module again recently — in the past I had to tack on an additional External virtual switch on top of the 'Internet' and 'Corpnet' Internal virtual switches, because I couldn't get the Internet Connection Sharing going to the 'Internet' Internal virtual switch for the INET and EDGE nodes.

Are these 131.107.* IP's meant to just be example IP's that you replace with IP's that align to your home network IP range? (From what I understand, that's what needs to happen if you want to get internet connection sharing to work, going off of [this example](http://www.technig.com/connect-hyper-v-machines-to-internet/).) If so that's fine, but just want to clear that up. :) I might submit a PR with some more comments in the example to make that clear.

Also — side question, if I have an External virtual switch and any number of Internal virtual switches (2 like in the Test Lab Guide example), it's still possible to share the internet connection from the physical NIC of the host and / or the External virtual switch to an Internal virtual switch, correct? Thanks!

**Comment by ryanspletzer** [comment]
For that side question, I played around and answered that myself. :)

**Comment by iainbrighton** [comment]
@ryanspletzer The 131.107.* addresses are the addresses that are used in the MS Test Lab Guides. You can change these addresses to suit your requirements, as needed.

I use the "new" Windows 10 container NAT functionality to enable internet access for the VMs. Unfortunately, this only supports a single subnet address at present  :-1:.

The 'Internal' switch types are used as this is the safest option for the examples. You can change these switches to 'External' virtual switches, if needed.

**Comment by ryanspletzer** [comment]
Got it, that makes sense. Thanks!
