### ISSUE TITLE
Windows 10 Enterprise 10586.420

### ISSUE THREAD

**Issue by ryanspletzer** [VirtualEngine/Lability#115]
In the default registered media, I noticed the LTSB of W10 Enterprise is registered -- might it be possible to also have the non-LTSB latest builds registered as well? (I realize these change often -- harder to maintain; and also would me having to maybe rename the existing W10 registered media with perhaps an appended _LTSB or something, or denoting the non LTSB with something.)

Also -- how do you go about getting those nice, static URL's to the ISO media? I looked around and the evaluation center gives me a link like:

http://care.dlservice.microsoft.com/dl/download/B/B/3/BB3611B6-9781-437F-A293-AB43B85C2190/10586.0.151029-1700.TH2_RELEASE_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_EN-US.ISO

and I don't know if that's static or not. I could just swap the care.dlservice.microsoft.com/dl portion of the URL for download.microsoft.com I suppose, if that's all it takes.

And if it is, I can just register it myself, nbd. :)

**Comment by kilasuit** [comment]
The URL you have there is the Static DL link from what I've found as well and clicking it does try to download the file.

You can Register it yourself or if you feel upto it you can add it into the media.json file and submit a PR here too :-)

**Comment by iainbrighton** [comment]
@ryanspletzer @kilasuit Yup - I change the URL to download.microsoft.com!

However we do need to come up with a solution for the Windows 10 naming convention. @csandfeld has mentioned this previously as well.

Now that we have the the 1507 and 1511 (and shortly 1607) builds, we need a way of naming these. Do we need a "latest" version and then specific builds? The latest media could then be updated to point to the latest official build.

I'm not sure whether there are evaluation ISOs for both the LTSB and CBB releases? I assumed (possibly incorrectly) that there would only be one branch made available for evaluation?

**Comment by ryanspletzer** [comment]
When I went to the TechNet eval site I had the option of picking the LTSB or the latest "Technical Preview" version of W10 Enterprise.

I actually made a small snippet I stuck in a gist to update the lab media registrations for W10 and WS2016 TP5, along with registering the latest CU hotfixes for both (which is SUPER nice from Microsoft for W10 / WS 2016, just have to apply one CU now to an image to stay current!):

https://gist.github.com/ryanspletzer/f8f41e4e6e35205a00ca36e16af0ca74

I think the hotfix URL's in that snippet are static, too.

I'm not sure you'd need to maintain *all* the past build versions necessarily -- but I think kind of aligning with what's available through the eval site makes sense. (I can't imagine they'll have multiple past versions of LTSB builds out there over time?)

I think the latest media + the LTSB build is probably fine.

**Comment by iainbrighton** [comment]
@ryanspletzer I've been over the eval center and had another look. There are the two releases, 1511 (build 10586) and LTSB (build 10240). I assume when the Anniversary Update ships, there will only be 1607 (build 147xx) and LTSB (build 10240) available for eval.

Therefore, we probably need to change the existing Win 10 media to the latest release (1511) and add a LTSB-specific media entry for the long-term servicing branch? For example, add `WIN10_x64_Enterprise_LTSB_EN_Eval` and `WIN10_x64_Enterprise_LTSB_EN_Eval` as additional media options?

**Comment by iainbrighton** [comment]
@ryanspletzer Is there any easy way of tracking the latest cumulative updates for each release? Pushing updates to the config files on a monthly basis is not something I would want to commit to.

**Comment by ryanspletzer** [comment]
@iainbrighton  re: LTSB that approach makes sense.

I hear ya re: monthly CU's, that would be a chore... It could maybe just put something in the docs around W10 / WS2016 to check for latest CU and perhaps a registration example. It seems like the W10 media ISO's themselves rev every few months, too anyways (February, April I think were the last two).

I know they have this page here that details the W10 monthly CU's which is nice, haven't seen something similar for WS2016 TP's but maybe once they RTM they'll have a page like this, too:

https://support.microsoft.com/en-us/help/12387/windows-10-update-history

**Comment by ryanspletzer** [comment]
@iainbrighton Oh, one thing to note that I ran into: I had to explicitly set $W10.ImageName = "Windows 10 Enterprise Evaluation Technical Preview" in that script because that string is actually what is keyed off of and listed in the WIM index in the evaluation media I got from TechNet for the latest version, so Lability wouldn't find it otherwise if I didn't explicitly set the ImageName to that. The LTSB version for Enterprise appears to be the "normal" named version but they decorate the latest version with this "Technical Preview" label, even though we're likely all using it regularly right now. :)

**Comment by iainbrighton** [comment]
@ryanspletzer I'm not entirely sure it's documented, but you can actually specify the WIM index - check out Line 217 in \Src\LabImage.ps1 :wink:. Therefore, if there's only a single image in the WIM, you could just use `1` in the `ImageName` property!

**Comment by kilasuit** [comment]
I had an issue with this and the 14925 MSDN ISO

Basically Dism reported Insider Preview whereas it came out to be Technical Preview

`#Doh`

**Comment by ryanspletzer** [comment]
Updated my gist for June 28, 2016 Windows 10 CU: 

https://gist.github.com/ryanspletzer/f8f41e4e6e35205a00ca36e16af0ca74

**Comment by iainbrighton** [comment]
@ryanspletzer Cool! Do you want to submit a PR to get these changes merged in?

Having a look through your Gist, the reason you had a "strange issue" is that the `CustomBootstrap` definition requires a `[string[]]` when defined in the media. This is a JSON serialisation/deserialisation issue.

There are differences between the media and node custom bootstrap definitions, see https://github.com/VirtualEngine/Lability/blob/dev/en-US/about_Bootstrap.help.txt#L102 and https://github.com/VirtualEngine/Lability/blob/dev/en-US/about_Bootstrap.help.txt#L127 for more context.

As a side-note, you could do this instead:
```powershell
Import-Module -Name Lability
$WIN10_x64_Enterprise_EN_Eval = @{
    Id = "WIN10_x64_Enterprise_EN_Eval";
    Architecture = "x64";
    MediaType = "ISO";
    Uri = "http://download.microsoft.com/download/B/B/3/BB3611B6-9781-437F-A293-AB43B85C2190/10586.0.151029-1700.TH2_RELEASE_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_EN-US.ISO";
    Checksum = "F9B3D3FAC8FD235C185B1C1F97F819EE";
    ImageName = "Windows 10 Enterprise Evaluation Technical Preview";
    Description = "Windows 10 64bit Enterprise Evaluation Technical Preview";
    Hotfixes = @(
        @{
            Id  = "windows10.0-kb3172985-x64_006b20fc4c418499afa25248edacff2ef7dab963.msu"
            Uri = "http://download.windowsupdate.com/d/msdownload/update/software/secu/2016/07/windows10.0-kb3172985-x64_006b20fc4c418499afa25248edacff2ef7dab963.msu"
        }
    )
    OperatingSystem = "Windows";
    CustomData = @{
        WindowsOptionalFeature = @('NetFx3')
        CustomBootstrap = @(
            "## Unattend.xml will set the Administrator password, but it won't enable the account on client OSes",
            "NET USER Administrator /active:yes;",
            "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force;",
            "## Kick-start PowerShell remoting on clients to permit applying DSC configurations",
            "Enable-PSRemoting -SkipNetworkProfileCheck -Force;"
        ) 
    }
}
Register-LabMedia @WIN10_x64_Enterprise_EN_Eval -Force
```
It makes it a little more readable as to what's going on IMHO. It achieves exactly the same result though!

**Comment by iainbrighton** [comment]
@ryanspletzer I've submitted #123 which adds RS1/1607 media and renames the existing media with LTSB. I was going to add in the latest cumulative (July 2016) update for the LTSB release, but can't appear to find a direct download link! Do you have this?

**Comment by ryanspletzer** [comment]
Cool, thanks @iainbrighton. Sorry, been busy lately! I just submitted [#127](https://github.com/VirtualEngine/Lability/pull/127) which adds the registrations for July 2016 CU's for 10240 LTSB media.

**Comment by ryanspletzer** [comment]
#129 is the same deal but for WS 2016 TP5, latest CU from June 28 (did not see a more recent one for that yet).

**Comment by ryanspletzer** [comment]
#131 is the same deal for Windows 10 August 9 CU for 1607 and LTSB media.

We can probably close this issue now? I'll try to pitch in and help with commits as new CU's arrive. I'd wind up updating my little diddy gist script anyways to update my own media so I might as well contrib it back. :)

**Comment by iainbrighton** [comment]
Closing - thanks for all your help 😃
