### ISSUE TITLE
Add ability to enable Guest Services as part of Configuartion file or on by default

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#116]
Facilitates my laziness in being able to transfer files using Copy-VMFile if this was enabled by default or configurable in the PSD1

**Comment by iainbrighton** [comment]
@kilasuit This was added in 0.9.9? There's a GuestIntegrationServices parameter on Set-LabVMDefault.

You can also set Lability_GuestIntegrationServices = $true on either the * or individual node level in the .psd1 file (the Lability_ bit isn't actually needed but helps with naming clashes).

Is this what you're after?

**Comment by kilasuit** [comment]
Haha - my bad as missed that completely
