### ISSUE TITLE
CONTRIBUTING.md - all rules in the one place

### ISSUE THREAD

**Issue by it-praktyk** [VirtualEngine/Lability#119]
I see - from other issues - e.g. issue #118 and #4 that some general rules for contributing to Lability should be discussed and stated.
## I propose create CONTRIBUTING.md file for Lability.

Good start point to discussion can be the article [Wrangling Web Contributions: How to Build a CONTRIBUTING.md](https://mozillascience.github.io/working-open-workshop/contributing/)

**Comment by iainbrighton** [comment]
@it-praktyk Yeah - that need doing too.. :wink:

**Comment by tigerfansga** [comment]
I don't mind helping with this. I've skimmed the article and can look at their examples. Just not sure what you would exactly want for your project

**Comment by it-praktyk** [comment]
Sorry, I don't care more about that issue.
