### ISSUE TITLE
Machines turn off at 1:00:00 hour run time?

### ISSUE THREAD

**Issue by quizard** [VirtualEngine/Lability#122]
I'm not sure what is causing this? It doesn't happen on my Windows 10 / Hyper-V 8.0. It only happens with virtual machines created with lability. Anyone else seeing this?

**Comment by iainbrighton** [comment]
Hi @quizard - this will happen if you use the default evaluation media and the machines do not have internet access. __If the evaluation copies cannot activate over the internet, they will shut down after an hour__. You have two primary options:

1. Provide internet access to the VMs via an external or NAT virtual switch or
2. Use alternative media by registering existing volume license VHD(X)s or ISOs.

Does this answer the question?

**Comment by quizard** [comment]
Perfect @iainbrighton !! I've been digging through code, looking at schtask, and just pulling my hair out wondering where this was coming from. The win10 / hyper-v 8 is using my MSDN media. Great project!

**Comment by iainbrighton** [comment]
@quizard Glad you like it! You can register your MSDN as defaults if have them. For obvious reasons, these can't be included by default :wink:.

**Comment by iainbrighton** [comment]
Closing. If you have any further questions, please open an issue 😃
