### ISSUE TITLE
Option to turn off Dynamic Ram on VM or VMDefault basis

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#132]
Some "applications" aren't fond of being made to use a VM with dynamic ram set.

Ideally we should be able to properly set this either on VM instance or as an additional LabVMDefault property.

**Comment by iainbrighton** [comment]
@kilasuit If I need to disable dynamic memory, I just set all the memory options to the same value. For example, to create a VM fixed to 4GB I use this:
```powershell
@{
    AllNodes = @(
        @{
            NodeName = 'FixedMemory';
            MinimumMemory = 4GB;
            StartupMemory = 4GB;
            MaximumMemory = 4GB;
        }
    }
}
```
I don't think that the `StartupMemory` value is required, but Lability will moan if the `StartupMemory` value is less than the `MinimumMemory` value (obviously!).

Does this work for you (documentation will still need updating) or do you think we need a more explicit option?

**Comment by kilasuit** [comment]
Indeed it does - thanks :-)
