### ISSUE TITLE
Remove reliance on included DSC modules

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#133]
I think that we should plan to remove the reliance of the included xHyperV & xPendingReboot and making these required modules in the Lability Module Manifest especially as the xDSC resources are all currently moving towards being HQRM Resource Modules.

**Comment by iainbrighton** [comment]
@kilasuit This is originally how it was, but I moved to bundling the resources! They have been moved internally for two main reasons:

* To avoid conflicts with locally installed DSC resource versions. We don't want to enforce a particular version of the xHyper-V or xPendingReboot modules upon anyone in case they're incompatible with a user's DSC configuration.
* Bugs fixes and new functionality are easier to add. The fixes/additions are pushed upstream to the public repositories, but it can take months to get changes merged in and made available in the PSGallery.

Do you still feel that these should be external dependencies?

**Comment by kilasuit** [comment]
@iainbrighton Regarding enforcing a particular version was that not in v4 timeframe because you couldn't have side by side modules installed anyway?

Also with the DSC modules and avoiding conflicts - if they are being downloaded to a cache resource location (perhaps C:\Lability\Resources as discussed in #106 then there should be no issue with conflicts etc and also users should be really be defining in their configurations the name and version of the resource module to be using and if its like my workflow they are very unlikely to be writing and compiling DSC configurations on a machine managed by DSC so I think that its an edge case where the modules required by Lability would conflict.

Regarding bug fixes, I do see your point however the pace has picked up with the resources lately and there are more people actively working on them which should help quicken these up and we could always add logic to be able to pull them from one of the builds if required at all.

**Comment by iainbrighton** [comment]
@kilasuit I think that we should circle back around to this once the xHyper-V, xComputerManagement and xPendingReboot resources are HQRMs and we've decided to drop support for Win 8.1 and 2012 R2?

**Comment by iainbrighton** [comment]
Closing out as I see no (current) need to "unbundle" the DSC resources. We can revisit this when we decide to no longer support Win 8.1/20212 R2 as hosts.
