### ISSUE TITLE
Install with MSDN Product key

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#134]
It may just be me (likey) but it seems that using custom media with an MSDN iso I'm trying to make use of the Product key never gets used so the resulting image isn't activated.

I believe (though could be wrong) that the Product Key needs adding as a property in the CustomData section??

**Comment by iainbrighton** [comment]
@kilasuit Correct - if specifying on the node configuration, it needs to specified in the CustomData hashtable:
```powershell
@{
    AllNodes = @(
        @{
            NodeName = 'ProductKey';
            CustomData = @{ ProductKey = 'ABCDE-1234-...' }
        }
    )
}
```
Having said that, I think there is something missing here. You can define a product key in the `CustomData` property when registering custom media (https://github.com/VirtualEngine/Lability/blob/dev/Src/LabMedia.ps1#L35). However, it looks like this is never actually used?! I'll do some checking and make sure that a product key defined in the media configuration is used.

**Comment by kilasuit** [comment]
I think that the if statement needs to be above where the $labMedia object gets created so that the $CustomData object has that property. https://github.com/VirtualEngine/Lability/blob/dev/Src/LabMedia.ps1#L73

We would also need to replicate this in Register-LabMedia too with an additional parameter but that's only a small thing

**Comment by iainbrighton** [comment]
@kilasuit Just to confirm - this is an issue with a ProductKey defined in a registered media entry? If you specify the ProductKey in the configuration .psd1 file, it is passed through successfully?
