### ISSUE TITLE
Add Linux options to Media.json

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#135]
Now Powershell is Available cross platform it would be great to be able to spin up an Ubuntu (& other distros) using Lability

**Comment by kilasuit** [comment]
Though using Register-LabMedia errors when -OperatingSystem is set to Linux and -MediaType is set to ISO

**Comment by it-praktyk** [comment]
Do you know [SetLinuxVM](http://www.setlinuxvm.com/) project?

@yusufozturk, thx for the great project!

**Comment by kilasuit** [comment]
@it-praktyk - I hadn't however I really am not a fan of .msi installs and as Lability does already have provision for some Linux items I feel that extending this would be quite beneficial.

**Comment by iainbrighton** [comment]
The reason you get an error when using ISO media is that installing Linux is a completely different process to installing Windows via a WIM image. To automate a Linux install requires creating a custom Kickstart ISO - and then booting the VM with the __ISO mounted__. This will require a change in internal logic to implement.

@kilasuit @it-praktyk What exactly would you like to see implemented to support Linux? Just the ability to boot with an ISO in the drive?

PS - Now wouldn't it be great if Windows had a native EXT filesystem driver so that we could access a Linux VM's disks when mounting a VHD(X)?!

**Comment by kilasuit** [comment]
> @kilasuit @it-praktyk What exactly would you like to see implemented to support Linux? Just the ability to boot with an ISO in the drive? 

@iainbrighton - this should be something that would be a minimum allowable - As this could allow me to have a small lab config that consists of Windows & *nix VM's

If we allow this then I think in Register-LabMedia it should throw a warning to inform that no configuration will be applied to the VM and that the functionality is just like attaching the ISO to a new VM

Obviously though we could always build an image vhd as well (thinking ahead) that already has PowerShell installed. Just gives us options in both directions.

**Comment by iainbrighton** [comment]
@kilasuit This will require having the ability to add a DVD/CD drive to a VM. This will need to be implemented in the xHyper-V resource. I've opened [an issue](https://github.com/PowerShell/xHyper-V/issues/63) to start this discussion.

**Comment by superdale007** [comment]
What about in the case of Kali-Linux...they provide a prebuild vhdx for downloading...All that would be needed is to set the configuration settings (1CPU/1MB RAM/NIC)?

**Comment by iainbrighton** [comment]
If you already have a VHD/X image then this can be added, here's an example of registering a [Citrix NetScaler VHD](https://gist.github.com/iainbrighton/7c5d4fe197cd6cce017da3e8293696c4).

Once [xVMDvdDrive](https://github.com/PowerShell/xHyper-V/pull/65) is merged, we can look at implementing the ability to create a blank VHDX and mount an ISO.

**Comment by iainbrighton** [comment]
Blank VHD(X) files can now be created and ISOs mounted in the latest dev release (#286). I'm not sure this still matters, but it should now be possible! 😀
