### ISSUE TITLE
New-LabVm command surfaces Admin Password to Verbose stream.

### ISSUE THREAD

**Issue by brycem** [VirtualEngine/Lability#140]
`PS C:\Windows\system32> $VerbosePreference="Continue"`
`PS C:\Windows\system32> New-LabVm -Name $name -MediaId $id -SwitchName $sw`
`#it executes, prompts for a password, then spews lots of verbose output including the following line:`
`'VERBOSE: [6:34:33 PM] Setting local administrator password to 'PwdShouldn'tAppearInLogsOrConsole...'.`
`#('PwdShouldn'tAppearInLogsOrConsole...' being the credential I supplied)`

I'd expect this to show as '*******' or simply 'VERBOSE: [6:34:33 PM] Setting local administrator password'

**Comment by iainbrighton** [comment]
@brycem I thought I'd got rid of this a long time ago! I was having trouble with "encrypting" the `unattend.xml` file. I'll get it removed. Thx.
