### ISSUE TITLE
.mof not created..

### ISSUE THREAD

**Issue by Naboo2604** [VirtualEngine/Lability#142]
...sound´s very cool tool, but i´m not able to get up and running - i tested it on my corp laptop (win10 1607 build) and a server with 2016TP5 (freshly installed) - what i done until now was:

Register-PSRepository -Name PSGallery -SourceLocation https://www.powershellgallery.com/api/v2/ -PublishLocation https://www.powershellgallery.com/api/v2/package/ -ScriptSourceLocation https://www.powershellgallery.com/api/v2/items/psscript/ -ScriptPublishLocation https://www.powershellgallery.com/api/v2/package/ -InstallationPolicy Trusted -PackageManagementProvider NuGet
(because tp5 get me "WARNING: unable to find module repos.." error)

Install-Module -Name Lability
Get-LabHostDefault
Set-LabHostDefault -ConfigurationPath D:\Lability\Configurations -HotfixPath D:\Lability\Hotfixes -IsoPath D:\Lability\ISOs
Start-LabHostConfiguration -Verbose    (everything was ok...)
Test-LabHostConfiguration -Verbose (everything ok - sometimes error on win10 about pendingreboot - think this is a problem with xPendingReboot resource..)
Copy NanoExample.ps1 and NanoExample.psd1 in D:\Lability\Configurations\
Install-Module xNetworking, xPSDesiredStateConfiguration
Get-LabVMDefault
Set-LabVMDefault -SystemLocale en-US -InputLocale de-AT -UserLocale en-US -StartupMemory 2GB -TimeZone "W. Europe Standard Time"
cd D:\Lability\Configurations
.\NanoExample.ps1
.\NanoExample.ps1 -Outputpath D:\Lability\Configurations -ConfigurationData .\NanoExample.psd1 

PROBLEM: no mof file created, no error message, simply nothing - second command creates a subdir "NanoExample" but it is also empty..

What i making wrong?

Many thanks for helping in advance,
Markus

**Comment by iainbrighton** [comment]
Hi @Naboo2604 I think there is an issue with TP5 Nano server, but this isn't your problem (yet!).
Try running the following instead:
```powershell
## Import the NanoExample configuration (you can't just run it!)
. D:\Lability\Examples.\NanoExample.ps1

## Compile the mofs (NanoExample is the configuration defined within NanoExample.ps1)
NanoExample -OutputPath D:\Lability\Configurations -ConfigurationData .\NanoExample.psd1


    Directory: D:\Lability\Configurations


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       16/09/2016     20:21           7188 NANO1.mof
-a----       16/09/2016     20:21           1150 NANO1.meta.mof
```

**Comment by Naboo2604** [comment]
Hi Iain,
aaargh - i read it at least 50times but always overseen the .ps1 in the second command i enter (arrow up is´nt always your friend) :smile: 
many thanks for help - in reference to my example above - these are the two working lines:

`. 'D:\Lability\Configurations\NanoExample.ps1'`
`NanoExample -Outputpath D:\Lability\Configurations -ConfigurationData .\NanoExample.psd1`

I wrote a "HowTo from scratch" with screenshots for the example above (maybe useful for Lability beginners like me): 
http://blog.mscloud.guru/2016/09/17/create-your-virtual-lab-environment-with-lability-howto/

thanks again for help.
br, Markus

**Comment by iainbrighton** [comment]
@Naboo2604 Thanks for the write up. I'm planning on adding a few links to existing articles in the project `readme.md` and will add yours 👍
