### ISSUE TITLE
Windows updates will no longer be available on the Microsoft Download Center

### ISSUE THREAD

**Issue by ryanspletzer** [VirtualEngine/Lability#143]
Yep.

https://mspoweruser.com/windows-updates-will-no-longer-be-available-on-the-microsoft-download-center/

Fun times. I'm actually gathering up links from monthly WS 2012 R2 roll ups for my own registration purposes. I'm going to try to get something together for a commit to update some things to future proof this...

W10 and WS2016 are fairly trivial to update because of the cumulative updates they put out every month.

**Comment by iainbrighton** [comment]
@ryanspletzer Aren't MS moving to the cumulative update model for Win 7, 2008 R2, 8.1 and 2012 R2 like they have with Win 10, from next month? Shouldn't this make things "easier"!?

**Comment by ryanspletzer** [comment]
@iainbrighton I know right! I wish it were that simple...

So for W7/2008 R2 they have a "convenience rollup" now which takes care of all the updates for the past few years. up through August 2016 I believe. (Sweet.) Based on what they've said, from here on out there's a monthly rollup for W7/2008 R2 that one can tack on, makes it easy(er), but I don't think they'll have a monthly CU for this, unfortunately. Also apparently .NET Framework stuff comes in a second monthly rollup....

https://blogs.technet.microsoft.com/windowsitpro/2016/08/15/further-simplifying-servicing-model-for-windows-7-and-windows-8-1/

Now, as I've looked into this for W8.1/2012 R2, there's no convenience rollup for it like W7/2008 R2. :( And they *used* to do monthly rollups for it starting in October 2013 timeframe through December 2014, but there's this stretch of time from Jan 2015 to April 2016 where there are no monthly rollups, then in May 2016 they started doing them again.

https://blogs.technet.microsoft.com/chad/2015/01/21/current-windows-server-2012-r2-windows-8-8-1-update-rollups/

http://social.technet.microsoft.com/wiki/contents/articles/23823.list-of-rollup-updates-for-windows-8-1-and-windows-server-2012-r2.aspx

W10/2016 are super duper easy because of the 1 CU you have to grab now. (Idk if .NET is still separate, in which case that would be 1 more monthly rollup to grab perhaps? Need to test / look into that.)

So ironically, W8.1/2012 R2 has now become more tedious to patch / gather a list of patches for than W7/2008 R2, ha. But I've been playing around, there is a [script](https://gist.github.com/ryanspletzer/a9022b3ef4c8fc338ee6b335e23fd361) (which I can't rightfully remember where I found this) for gathering up all the patches + their .cab URL's at Windows Update from a patched VM. I patched a WS 2012 R2 VM manually, and ran that script to get a list of links. It worked great. It didn't include .NET 4.5.2 / 4.6.1 stuff but that shouldn't be hard to gather up and add in.

I know typical practice for folks is to just maintain a sysprepped image, but with these I'm kinda interested in maintaining registrations such that I can go from zero to patched VM and not have to do that. Not that that *has* to get worked into the Lability default registrations, but I know at least that the download.microsoft.com links will have to get replaced with download.windowsupdate.com links for the long term.

**Comment by iainbrighton** [comment]
@ryanspletzer I'm thoroughly confused. I guess we'll have to see how it pans out.

Now - I'd like to be able to create from scratch, a patched and SYSPREP'd VHD(X) if/as needed. I don't think that this functionality should all be in Lability, but Lability could certainly be used as the platform to create these "images". For example, I think that there might need to be some additional steps to get .NET in there?

**Comment by ryanspletzer** [comment]
@iainbrighton I largely agree. What I've been doing a lot on the side is maintaining small registration scripts in my own gists that tacks on hotfixes to existing media (and I have some plans to stick my own media from MSDN up in my OneDrive so I can register non-evaluation, licensed media with URL's pointed at my own hosted ISO's there).

As evidenced by this gist, there are a LOT of patches for WS 2012 R2, so maintaining this in Lability could prove very cumbersome.

https://gist.github.com/ryanspletzer/b589b75f8796c517ad6c8b537841683e

But I will try to get us some links to put into the base default registrations that go to the Windows Update site vs. Microsoft Download Center which is apparently going away.

BTW -- can I mention how happy I am that WS 2016 is officially out now and I only have to worry about 1 CU at a time!!! :D I mess around with 2012 R2 still quite a bit since that's the main thing in our org and in Azure still, but man, the world is getting better.

**Comment by iainbrighton** [comment]
@ryanspletzer I'm sure you've probably already seen [this](https://blogs.technet.microsoft.com/windowsitpro/2016/10/07/more-on-windows-7-and-windows-8-1-servicing-changes/), but just in case.. 😉

**Comment by ryanspletzer** [comment]
@iainbrighton I'm back. :) I've had some time to refocus efforts on using Lability (using it to test some DSC resources I'm writing) -- I think it's safe to close this thread.

Gathering up the image-able .cab updates was a scripting exercise that I've worked through (started with WSUS offline's to get a list of security updates, then used WSUS COM api to query for remaining recommended updates). Once you have your static update list it's fairly easy to pop new updates on the end for a given OS version when second Tuesday (or whenever these days it seems) rolls around. (WIN10/2016 is trivial to get a list together update, especially the latest build; WIN81/2012R2 took some elbow grease, but thankfully from here on out it should be 1 monthly rollup to add to the list.)

For those who may be curious, reference in my personal Scripts repo (gists were getting too hard to find / reference stuff):

[Registration Data File](https://github.com/ryanspletzer/Scripts/blob/dev/PowerShell/RegisterLabilityMediaAndHotfixesScript.psd1) -- Hotfixes points to local exported .clixml files from registered (Get-LabMedia -Id <Id>).Hotfixes object (because a lot were repeated) that the next script imports.

[Registration Script](https://github.com/ryanspletzer/Scripts/blob/dev/PowerShell/RegisterLabilityMediaAndHotfixesScript.ps1) -- reads in Data file and registers the media / hotfixes. (Note: I host my own custom media from MSDN in OneDrive and have a script for generating static links to those things referenced within, can adjust to your desires)

I think the baked-in registrations in Lability probably only need to get updated when TechNet updates their Eval media (which probably only happens for new major builds like 1607).

**Comment by iainbrighton** [comment]
@ryanspletzer welcome back! That would make a great talk/blog post one day!

I would love to automate the creation of patched VHDX files with the latest updates. I did start looking a while ago with [WSUS Offline](http://download.wsusoffline.net/), but work and other commitments have stalled that effort for the time being 😞.

**Comment by michaeltlombardi** [comment]
@iainbrighton, for managing deployment artifacts in a sane, repeatable, infrastructure-as-code style, you may want to take a look at [Packer](https://www.packer.io/intro/) - they finally added official support for the hyper-v builder a while ago. Probably the best tool I've seen for solving that problem.

Packer for artifacts and then lability to stand up a lab using them seems like a great combo to me.

**Comment by iainbrighton** [comment]
@michaeltlombardi I looked at Packer ages ago and it's Hyper-V support was lacking. I'll have to circle back around and have another look!
