### ISSUE TITLE
n00b question: How do you get started?

### ISSUE THREAD

**Issue by heartfrappe** [VirtualEngine/Lability#144]
I've tried running the Build.PSake.ps1 file and found that I needed to install PS5. Did that.
Now, I'm getting a new error:
The script 'Build.PSake.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: VirtualEngine.Build.
    + CategoryInfo          : ResourceUnavailable: (Build.PSake.ps1:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptRequiresMissingModules

I've tried running 'Install-Module -Name VirtualEngine.Build' and I get a "no match was found" result...

What am I missing here?

I'm running a fresh install of Windows Server 2012 R2 and the current master branch.

**Comment by iainbrighton** [comment]
@heartfrappe You don't need to run the PSake build script! Realistically you have 2 options:

* Upgrade to WMF 5
 * You can then run `Install-Module Lability` and install from the PowerShell Gallery.
* Download the Zip file
 * Extract it to `C:\Program Files\WindowsPowerShell\Modules\` directory (or your module path).

If you download the Zip the directory structure should look like this:
```powershell
PS C:\Users\Iain> ls 'C:\Program Files\WindowsPowerShell\Modules\Lability\'


    Directory: C:\Program Files\WindowsPowerShell\Modules\Lability


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       07/09/2016     17:44                .vscode
d-----       07/09/2016     17:44                Config
d-----       07/09/2016     17:44                DSCResources
d-----       07/09/2016     17:44                en-US
d-----       07/09/2016     17:44                Examples
d-----       07/09/2016     17:44                Lib
d-----       07/09/2016     17:44                Src
d-----       07/09/2016     17:44                Tests
-a----       06/09/2016     09:28           3328 Build.PSake.ps1
-a----       06/09/2016     09:28          15367 Lability.png
-a----       06/09/2016     09:28           1887 Lability.psd1
-a----       06/09/2016     09:28           2156 Lability.psm1
-a----       06/09/2016     09:28           1089 LICENSE
-a----       06/09/2016     09:28           9694 Readme.md
-a----       06/09/2016     09:28          16274 Resources.psd1
```
You're good to go when you can run the following and get a response:
```powershell
PS C:\Users\Iain> Get-Module -Name Lability -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.10.0     Lability                            {Start-Lab, Stop-Lab, Reset-Lab, Checkpoint-Lab...}

PS C:\Users\Iain>
```
If you have any more problems, let me know 😃

**Comment by iainbrighton** [comment]
@heartfrappe Did this help?

**Comment by iainbrighton** [comment]
Closing. Please reopen if you are still struggling.
