### ISSUE TITLE
Bootstrap looking for wrong version of module

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lability#147]
Ran into an issue the other day, where a VM generated from my config, had version 2.12.0.0 of the xNetworking module installed, but the .mof expected version 2.11.0.0.

I had version 2.11.0.0 of the module installed on my host (where I authored and ran my config) but 2.12.0.0 ended up inside the VM. I assume (but am not sure) that it downloaded 2.12.0.0 to the ModuleCache folder, and grabbed it from there.

The DSCResource part of the NonNodeData section in the .psd1 was grabbed from the TestLabGuide.psd1 example.

I suppose I could have worked around the issue by using **RequiredVersion** instead of **MinimumVersion** to ensure it matched the module version on the host. It does raise a question with me though - how do we easily ensure, that the host has the same version of the module, as those that will be injected into the VM - and vice versa. To that end I wonder if we should have a function to install modules on the host, based on the info in a .psd1 file (or do we already have that, and I am missing the obvious?)

I'm not sure if this is to be considered as a bug, but thought I would log it anyway 😄

**Comment by iainbrighton** [comment]
@csandfeld Yes - I've run into this before, but is only an issue where you're compiling the MOFs on the host machine.  You have 2 options:

* Remove the `DSCResources` definition from your configuration data.
 * ___You will need to install___ the required DSC resources on the host where you're compiling the mofs
 * Lability will then just copy all the DSC resources registered on the box (as was the old behaviour).
* Set a `RequiredVersion` of all modules in configuration document.
 * Lability will always copy this version of the DSC resources into the VHDX, _but_
 * ___You will need to install___ the required DSC resources on the host where you're compiling the mofs
 * You could still end up with a version mismatch with this method 😞 

As for the "we should have a function to install modules on the host" comment, have you looked at the [LabilityBootstrap](https://github.com/VirtualEngine/LabilityBootstrap) module or the [Install-LabModule](https://github.com/VirtualEngine/LabilityBootstrap/blob/master/Src/Public/Install-LabModule.ps1) function in particular? 😉. I would be interested to see if you think this should be moved into this module instead.

**Comment by csandfeld** [comment]
Had not had a look at LabilityBootstrap. Haven't tested, but Install-LabModule looks promissing. I would not mind having everything Lability in one mode, but from your perspective, what would be the pros/cons of maintaining two modules, versus combining into one?

**Comment by iainbrighton** [comment]
@csandfeld It's certainly a fine line and Lability was never intended to be used to compile configurations. 

However, I have some code that will compile configurations in parallel and this certainly should not be in the LabilityBootstrap module either. Does that mean I need a 3rd module?!

1. Install and compile configurations
2. Deploy configurations (Lability)
3. Create bootstrap ISO/manually bootstrap existing VMs, e.g. VMware (LabilityBootstrap)

Do you think that 1 and 2 could/should be merged? Thoughts?

**Comment by csandfeld** [comment]
I normaly write/compile configs on the same system I use to deploy them (my own client PC), and from that perspective it would be fine to have everything in one module. On the other hand, if configurations are used on other systems, and mofs are precompiled, it would not be necessary.

As I think of it now, having it in separate modules might actually be a good thing, as the "Lab Creator" module might not need  "#Requires -RunAsAdministrator". But then again, it might also mean having to maintain identical helper functions in both modules (assuming some operations might be similar accross both modules)

**Comment by iainbrighton** [comment]
Closing this out as #153 has been added.
