### ISSUE TITLE
Question: How to add extra disk(s) to a lab VM?

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lability#149]
I may me missinging something obvious - but how do you create a lab VM with multiple disks (or is it even possible)?

**Comment by iainbrighton** [comment]
@csandfeld Nope, you're not missing anything. This is a problem with the underlying Hyper-V DSC resources as they don't support attaching multiple disks to a VM 👎.

It's on my (extremely long) list of things to do - hence the issues about making the DSC resources more granular.

**Comment by csandfeld** [comment]
Bugger ... well nothing to do about that at this point then - thanks @iainbrighton
