### ISSUE TITLE
Register-LabMedia

### ISSUE THREAD

**Issue by quizard** [VirtualEngine/Lability#151]
I am successfully adding custom media using 

Register-LabMedia -Id 2012R2MSDN -MediaType "ISO" -Uri 'http://myurl/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso' -Architecture 'x64' -Description 'MSDN2012R2' -ImageName 'MSDN2012r2' -Filename 'en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso' -Checksum '78BFF6565F178ED08AB534397FE44845' -Hotfixes @{Id='Win8.1AndW2K12R2-KB3134758-x64.msu';Uri='https://download.microsoft.com/download/2/C/6/2C6E1B4A-EBE5-48A6-B225-2D2058A9CEFB/Win8.1AndW2K12R2-KB3134758-x64.msu'} -Force

But when I use it in my config I am hitting another small roadblock 

VERBOSE: [10:05:52 PM] Mounting disk image 'C:\Lability\ISOs\en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso'.
VERBOSE: [10:05:52 PM] Locating WIM image 'MSDN2012r2' index.
VERBOSE: [10:05:55 PM] Applying Windows Image '0' to 'd:\lab\mastervhd\2012r2msdn.vhdx'.
New-LabImage : Either the Name or Index parameter is required
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.9.11\Src\LabVM.ps1:292 char:27
+ ... ef] $null = New-LabImage -Id $node.Media -ConfigurationData $Configur ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-LabImage
 
WARNING: [10:05:56 PM] Removing incomplete image 'D:\lab\MasterVHD\2012R2MSDN.vhdx'.

**Comment by csandfeld** [comment]
Hi @quizard ,

I think the problem you see, is because the ImageName you specified with Register-LabMedia, does not match an image name in the install.wim on the ISO you are pointing to.

Try the following to list available images in the WIM (in this case I list images from the 2016 Eval ISO):

```PowerShell
$ImagePath = 'D:\Lability\ISOs\2016_x64_EN_Eval.iso'
$Mount = Mount-DiskImage -ImagePath $ImagePath -StorageType ISO -PassThru
Get-WindowsImage -ImagePath "$(($Mount | Get-Volume).DriveLetter):\sources\install.wim"
$Mount | Dismount-DiskImage



ImageIndex       : 1
ImageName        : Windows Server 2016 SERVERSTANDARDCORE
ImageDescription : Windows Server 2016 SERVERSTANDARDCORE
ImageSize        : 8.840.650.521 bytes

ImageIndex       : 2
ImageName        : Windows Server 2016 SERVERSTANDARD
ImageDescription : Windows Server 2016 SERVERSTANDARD
ImageSize        : 14.858.983.050 bytes

ImageIndex       : 3
ImageName        : Windows Server 2016 SERVERDATACENTERCORE
ImageDescription : Windows Server 2016 SERVERDATACENTERCORE
ImageSize        : 8.905.611.811 bytes

ImageIndex       : 4
ImageName        : Windows Server 2016 SERVERDATACENTER
ImageDescription : Windows Server 2016 SERVERDATACENTER
ImageSize        : 14.857.373.611 bytes
```

**Comment by quizard** [comment]
I'm building again! Thank you csandfeld!

**Comment by csandfeld** [comment]
👍

**Comment by tansei** [comment]
maybe I'm doing something wrong, but I've tried to follow the https://github.com/csandfeld suggestion, 
was thrown with following output:
`ImageIndex         : 1
ImageName         : Windows 10 Enterprise 2016 LTSB Evaluation
ImageDescription : Windows 10 Enterprise 2016 LTSB Evaluation
ImageSize            : 12 118 403 494 bytes
`
and when I'm staring to provision the VM as standalone one with following commandlet
`New-LabVM -Name w10-ltsb -MediaId WIN10_x64_Enterprise_LTSB_EN_Eval (some regular parameters which works for 2016_x64_Datacenter_EN_Eval media`

and within lability 0.12.4 it still throws an error message:
`Expand-LAbImage : Either the Name or Index parameter is required
At line:171 char:17
+ Expand-LabImage @expandLAbImageParams;
   + FullyQualifiedErrorId: Microsoft.PowerShell.Commands.WriteErrorException,Expand-LabImage`

can someone please drop some advise, here ?

**Comment by codykonior** [comment]
I came across something weird today. I have the same ISO on two machines - one is Windows 10 LTSB (1607) and the other is Windows 10 current (1809).

The above commands give two different ImageName responses. One is "Windows Server 2012 Standard Evaluation (Server with a GUI)", the other is "Windows Server 2012 SERVERSTANDARD".

If someone else has this issue use a number (the index of the one you want to use) rather than the name.
