### ISSUE TITLE
Add Lability Module Caching cmdlets

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#153]
Now that Lability is downloading and caching PowerShell and DSC resource modules, we could do with some additional cmdlets to manage these (currently I have to manipulate the cache directly in the filesystem).
- Get-LabModule(Cache) - Returns cached modules
- Remove-LabModule(Cache) - Deletes a cached module
- Clear-LabModuleCache - Empties all cached modules

@csandfeld If we think that Lability is the correct place, we could add the following too?:
- Install-LabModule - Registers all required cached modules defined in a Lability configuration
  - Used to enable compiling MOFs on the Lability host
  - Should default to CurrentUser scope
- Uninstall-LabModule - Unregisters all modules defined in a Lability configuration
  - Should default to CurrentUser scope
  - Might be better just deleting all user-scoped modules?!

**Comment by csandfeld** [comment]
Not sure it gets you closer to a decission, but see my comment in #147 :-)
