### ISSUE TITLE
New-LabImage fails every time at "Adding Windows feature(s) 'NetFx3' to image 'J:\'

### ISSUE THREAD

**Issue by heartfrappe** [VirtualEngine/Lability#165]
I have successfully created a Windows Server 2012 R2 MasterVirtualHardDisk. I'm attempting to create a Windows 10 Enterprise LTSB MAsterVirtualHardDisk as well and it fails at the same point no mater what I do. I've downloaded and installed the Windows 8.1 DISM and I'm still getting the error.

PS C:\Windows\system32> New-LabImage -Id WIN10_x64_Enterprise_LTSB_EN_Eval -Force -Verbose
VERBOSE: [10:55:57 AM] Resource 'D:\Lability\ISOs\WIN10_x64_ENT_LTSB_EN_Eval.iso' checksum matches '6CD2F47F2C32FAA7BE85F1DC81AF3220'.
VERBOSE: [10:55:57 AM] Creating disk image 'Windows 10 64bit Enterprise LTSB English Evaluation'.
VERBOSE: [10:55:57 AM] Creating disk image 'D:\Lability\MasterVirtualHardDisks\WIN10_x64_Enterprise_LTSB_EN_Eval.vhdx'.
VERBOSE: [10:55:59 AM] Mounting disk image 'D:\Lability\MasterVirtualHardDisks\WIN10_x64_Enterprise_LTSB_EN_Eval.vhdx'.
VERBOSE: [10:55:59 AM] Initializing disk image 'D:\Lability\MasterVirtualHardDisks\WIN10_x64_Enterprise_LTSB_EN_Eval.vhdx'.
VERBOSE: [10:56:01 AM] Creating 'EFI' disk partition.
VERBOSE: [10:56:01 AM] Formatting 'EFI' disk partition.
VERBOSE: [10:56:03 AM] Creating 'MSR' disk partition.
VERBOSE: [10:56:03 AM] Creating 'Windows' disk partition.
VERBOSE: [10:56:03 AM] Formatting 'Windows' disk partition.
VERBOSE: [10:56:12 AM] Mounting disk image 'D:\Lability\ISOs\WIN10_x64_ENT_LTSB_EN_Eval.iso'.
VERBOSE: [10:56:12 AM] Locating WIM image 'Windows 10 Enterprise Evaluation' index.
VERBOSE: [10:56:13 AM] Applying Windows Image '1' to 'D:\Lability\MasterVirtualHardDisks\WIN10_x64_Enterprise_LTSB_EN_Eval.vhdx'.
VERBOSE: [11:09:02 AM] Adding Windows feature(s) 'NetFx3' to image 'J:\'.
New-LabImage : To service this Windows image requires the latest version of the DISM. See http://go.microsoft.com/fwlink/?LinkId=293395 to find the latest version of 
DISM, 
and http://go.microsoft.com/fwlink/?LinkId=293394 to learn how to install the latest version of DISM from the ADK on your computer.
At line:1 char:1
+ New-LabImage -Id WIN10_x64_Enterprise_LTSB_EN_Eval -Force -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-LabImage
 
WARNING: [11:09:42 AM] Removing incomplete image 'D:\Lability\MasterVirtualHardDisks\WIN10_x64_Enterprise_LTSB_EN_Eval.vhdx'.

**Comment by heartfrappe** [comment]
Turns out this happens with the Server 2016 image as well... Surely, I'm making a mistake somewhere...

PS D:\Lability\Configurations> New-LabImage -Id 2016_x64_Datacenter_EN_Eval -Force -Verbose
VERBOSE: [9:39:11 PM] Resource 'D:\Lability\ISOs\2016_x64_EN_Eval.iso' checksum matches '18A4F00A675B0338F3C7C93C4F131BEB'.
VERBOSE: [9:39:11 PM] Creating disk image 'Windows Server 2016 Datacenter 64bit English Evaluation'.
VERBOSE: [9:39:11 PM] Creating disk image 'D:\Lability\MasterVirtualHardDisks\2016_x64_Datacenter_EN_Eval.vhdx'.
VERBOSE: [9:39:12 PM] Mounting disk image 'D:\Lability\MasterVirtualHardDisks\2016_x64_Datacenter_EN_Eval.vhdx'.
VERBOSE: [9:39:12 PM] Initializing disk image 'D:\Lability\MasterVirtualHardDisks\2016_x64_Datacenter_EN_Eval.vhdx'.
VERBOSE: [9:39:13 PM] Creating 'EFI' disk partition.
VERBOSE: [9:39:13 PM] Formatting 'EFI' disk partition.
VERBOSE: [9:39:14 PM] Creating 'MSR' disk partition.
VERBOSE: [9:39:15 PM] Creating 'Windows' disk partition.
VERBOSE: [9:39:15 PM] Formatting 'Windows' disk partition.
VERBOSE: [9:39:18 PM] Mounting disk image 'D:\Lability\ISOs\2016_x64_EN_Eval.iso'.
VERBOSE: [9:39:18 PM] Locating WIM image 'Windows Server 2016 SERVERDATACENTER' index.
VERBOSE: [9:39:20 PM] Applying Windows Image '4' to 'D:\Lability\MasterVirtualHardDisks\2016_x64_Datacenter_EN_Eval.vhdx'.
VERBOSE: [9:51:00 PM] Adding Windows feature(s) 'NetFx3' to image 'O:\'.
New-LabImage : To service this Windows image requires the latest version of the DISM. See http://go.microsoft.com/fwlink/?LinkId=293395 to find the latest version of 
DISM, 
and http://go.microsoft.com/fwlink/?LinkId=293394 to learn how to install the latest version of DISM from the ADK on your computer.
At line:1 char:1
+ New-LabImage -Id 2016_x64_Datacenter_EN_Eval -Force -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-LabImage

**Comment by iainbrighton** [comment]
@heartfrappe What OS are you running on? It looks like it's probably Win 8.1/Server 2012 R2. If so you'll need to do the following to build Win 10 and Server 2016 images:

* Install the [Win 10 ADK](https://developer.microsoft.com/en-us/windows/hardware/windows-assessment-deployment-kit).
 * I'd go with the 1607 Anniversary Update version
* Make sure you're running the latest v0.10.1 Lability release
* Run `Set-LabHostDefault -DismPath <PathToAdk\Microsoft.Dism.PowerShell.dll>`
 * It defaults to the in-box DISM version and needs to be changed.

This will configure Lability to use the Win 10 ADK instead of the built-in Win 8.1 DISM cmdlets.

**Comment by heartfrappe** [comment]
Trying now. Hold please, your call is very important to us. :)

Especially if it works... I'm LOVING this lab builder so far with 2012R2.

**Comment by heartfrappe** [comment]
Just realized I didn't answer your question. It's 2012R2 for the host.

**Comment by iainbrighton** [comment]
In which case, you'll definitely need the ADK imaging components installed :)

**Comment by heartfrappe** [comment]
Which dll do I need to point to? the x86, arm64 (doubtful), or the amd64 (I'm guessing this one)

**Comment by iainbrighton** [comment]
Correct – the \amd64\ one!

**Comment by heartfrappe** [comment]
Seems to be working, but I'm getting an error at certain points during the process. (See screen shot attached)

The vhdx files are still being generated though... Any thoughts on the message?
![after installing 10 adk](https://cloud.githubusercontent.com/assets/20590487/19994838/fdb212de-a21f-11e6-9692-20de3795e52b.png)


Title: powershell_ise.exe - System Error
Error: The program can't start because SetupPlatform.dll is missing from your computer. Try reinstalling the program to fix this problem.
Option(s): OK

**Comment by iainbrighton** [comment]
Not seen that one before. I do know that getting PowerShell to use a specific DISM version is not as easy as it should be!

You WILL need to restart PowerShell after running Set-LabHostDefault. Can you also try running in PowerShell.exe (not the ISE) and let me know if the same thing happens?

**Comment by heartfrappe** [comment]
Seems to want to work, but the new media it needed to download failed on download.

Are you aware of the issue where it doesn't unmount the iso on error? It wil remove the failed vhdx, but the iso will remain mounted each time you run. I know because I had 5 virtual drives mounted a little bit ago... :)

I'll let you know if the regular PowerShell works tomorrow. I'm going to bed now.

**Comment by iainbrighton** [comment]
@heartfrappe Yes - I've seen that. I'll log that one as a new issue and get it fixed.

**Comment by heartfrappe** [comment]
Seems to work fine in regular PowerShell. Maybe it's an issue with ISE. I thought I saw the scripts being demoed in ISE during one of the DEVOPS broadcasts... oh well. Thanks for the help!

**Comment by iainbrighton** [comment]
Yep, but not the new ADK/DISM support bit. Have you tried in the ISE after restarting it?

**Comment by heartfrappe** [comment]
I tried restarting the server and I'm still getting the error above in the ISE. It seems to still do the task, but the error comes up and halts until you click OK.

**Comment by iainbrighton** [comment]
I'll need to do some testing of the Win 10 ADK in the ISE. If you don't need .Net you can always register your own media without it.

**Comment by iainbrighton** [comment]
@heartfrappe I can recreate this issue, but it only appears in the ISE - not in `powershell.exe`. I'll see whether I can get it resolved, although the Google-Bing machine doesn't give me any clues.. 😢

**Comment by BristleBeard** [comment]
I'm getting this behavior trying to create a Win10 image, and I'm running on a 2016 server. I'm not getting an error about DISM, but I do get 'Cannot validate argument on parameter 'Id'. The argument is null or empty. 

Every other image has been created without issue, except Win10.  I'm not using ISE, but I am entering a PSSession from a Win10 client to do the work.

```
new-labimage : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is not null or empty, and then
try the command again.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-LabImage
```

**Comment by iainbrighton** [comment]
@BristleBeard How are you calling New-LabImage and are you using the latest dev build or the Gallery published version?

**Comment by BristleBeard** [comment]
PSGallery. I literally did an Install-Module to get it installed on my machines.  I get the same behavior when using a Win10 or Server 2016 client.

**Comment by iainbrighton** [comment]
I've not heard any other reports. What build numbers (`$PSVersionTable.BuildVersion`) are you using?

**Comment by BristleBeard** [comment]
@iainbrighton 10.0.14393.953 and 10.0.15063.296

**Comment by iainbrighton** [comment]
Closing this one out. There is nothing that I can find on the t'interwebs relating to this. I have added a `Known Issues` section to README.md.
