### ISSUE TITLE
Any way to update the Master VM VHDX file?

### ISSUE THREAD

**Issue by heartfrappe** [VirtualEngine/Lability#169]
Just curious if there was a way to bootstrap all of Windows Updates in to the Master VM VHDX as I just booted one up for the first time and it has 239 updates waiting for the first round...

Can I mount it, update it, sysprep it, and leave i back in the Master folder?

**Comment by iainbrighton** [comment]
@heartfrappe You can certainly replace the master VHDX in the `\Lability\ParentVirtualHardDisks` directory if you wish!

I guess the "correct way" would be to create your SYSPREP'd VHDX (however you choose to do this is up to you) and register it using the `Register-LabMedia` command. There's an example of registering a [custom Win 7 VHDX here](https://gist.github.com/iainbrighton/aff12e50f2929da50d667ee8404fc6bf). You can override the built-in/default media if you use the same `-Id` and use `-Force`.

More information is available in the `\Lability\en-US\about_Media.Help.txt` file too.
