### ISSUE TITLE
Module specification ignores MaximumVersion

### ISSUE THREAD

**Issue by dbroeglin** [VirtualEngine/Lability#170]
I just got hit by the fact that a new xNetworking module was released with version 3.0.0 a few days ago which is incompatible with version 2.7.0. I explicitly installed version 2.7.0 on the host with the following command:

```
Install-Module xNetworking -MinimumVersion 2.7.0 -MaximumVersion 2.7.0 
```

and changed the specification in the PSD file to :

```
    NonNodeData = @{
        Lability = @{
            DSCResource = @(
                @{ Name = 'xNetworking'; MinimumVersion = '2.7.0.0'; MaximumVersion = '2.7.0.0'; }
````
However, it is not taken into account by Lability:

```
VERBOSE: [1:12:30 PM] Module 'xNetworking' v2.7.0.0 or later was not found in the module cache or -Force was specified.
VERBOSE: [1:12:30 PM] Downloading resource 'http://www.powershellgallery.com/api/v2/package/xNetworking' to 'C:\ProgramData\Lability\Modules\xNetworking.zip'.

...

PS Z:\windows-lab2> dir "$((Get-LabHostDefault).ModuleCachePath)/xNet*"
-a----       11/14/2016   1:12 PM         123957 xNetworking-v3.0.0.0.zip
```

It took me quite a while to understand what was happening. It looks like `InvokeModuleCacheDownload` does not take the MaximumVersion parameter into account and does not fail. It was silly of me not to think of, at least, trying `RequiredVersion` however, I think others may fall in the same trap. It looks like `ResolvePSGalleryModuleUri` can only download a _required_ version or the latest. However, maybe an error message when `MaximumVersion` is present could  prevent further misunderstandings. What do you think ?

**Comment by kilasuit** [comment]
Thanks for reporting this - I can see where the issue is and will look to add in the functionality and tests to confirm the fix in the coming days

**Comment by iainbrighton** [comment]
Correct - there is no MaximumVersion key. I always use the RequiredVersion key, but can see where the confusion comes from. We can update the documentation and/or add a MaximumVersion key as necessary. 

If we choose add a new key, we need to remember that it's just a hashtable and there is no way of enforcing the equivalent of parameter sets. Therefore, we would have to test and either throw or warn, if a user specified both MaximumVersion and RequiredVersion keys.

**Comment by dbroeglin** [comment]
I would be inclined to, at least, throw if some parameter is provided that is not expected. Even just to ensure "MinmumVersion" would be catched. However, I'm not sure where that should go however. Maybe, in `InvokeModuleCacheDownload` or in the `InvokeModuleDownloadFromGitHub` and `InvokeModuleDownloadFromPSGallery`. For both methods there is a _splat_ but with a _catchall_ parameter `[Parameter(ValueFromRemainingArguments)] $RemainingArguments`. Maybe you should just remove those _catchalls_ and remove the Hash contents that should not be present in the splat like `$moduleInfo['Provider']`.

I'm sorry, I'm just throwing ideas around. I'm not familiar enough with the code to have more helpful suggestions. I like the idea that the Hash mimics the usual function parameters it helps ensure coherence between the command line of say, `Install-Module` with which most people should be familiar with and how specifications occur in Lability.

**Comment by iainbrighton** [comment]
In this instance (and off the top of my head) it will probably have to be added to the `GetModuleCache`, `TestModuleCache` and `InvokeModuleCacheDownload` methods.
