### ISSUE TITLE
How to uninstall Lability module ? 

### ISSUE THREAD

**Issue by andlo** [VirtualEngine/Lability#173]
subject says it all ?

**Comment by iainbrighton** [comment]
@andlo Well that depends on how it was installed! If you installed Lability from the PowerShell Gallery you can run a `Remove-Module -Name Lability -Force`. If you manually installed it by downloading/extracting the .zip file, you'll need to remove that entire directory. You can find the installation path by running `Get-Module -Name Lability -ListAvailable | Format-List`.

Does this answer your question?

**Comment by andlo** [comment]
@iainbrighton Thanks. It didnt work, but I got messed up im modules and some modules couldnt be uninstalled. Iwe got it under control now. :)
