### ISSUE TITLE
more than one networkinterface

### ISSUE THREAD

**Issue by andlo** [VirtualEngine/Lability#176]
I want to setup a gateway server - a windows server whit Routing feature enabled.

I configure two interfaceses for the HyperV host whith:
 Network           = @(
        @{
          Name = 'Internal'
          Type = 'Internal'
        }
        @{
          Name              = 'External'
          Type              = 'External'
          NetAdapterName    = 'Ethernet 2'
          AllowManagementOS = $true
        }
      )
My Gateway is setup like this:
   @{
      NodeName                = 'GW'
      IPAddress               = '10.0.0.254'
      DnsServerAddress        = '10.0.0.1'
      Role                    = 'GW'
      Lability_StartupMemory  = 1Gb
      Lability_ProcessorCount = 1
      Lability_Media          = '2016_x64_Standard_EN_Eval'
      Lability_SwitchName     = 'Internal', 'External'
    }

But when booting this machine up, sometimes the machine gets "Ethernet" on internal and "Ethernet 2" on external, and sometimes the otherway round.
How do I make sure that first interface is internal and second is external ?

My mashine is configured like this:
 node $AllNodes.Where({
      $_.Role -in 'GW'
  }).NodeName {
    {
      WindowsFeature RemoteAccess
      {
        Name = 'RemoteAccess'
        Ensure = 'Present'
        #IncludeAllSubFeature = $true
        DependsOn = '[xComputer]DomainMembership'
      }
      
      WindowsFeature Routing
      {
        Name = 'Routing'
        Ensure = 'Present'
        #IncludeAllSubFeature = $true
        DependsOn = '[xComputer]DomainMembership'
      }
     

      Script Routning
      {
        SetScript = 
        { 
          Set-Service -Name RemoteAccess -StartupType Automatic
  
          netsh routing ip nat install
          netsh routing ip nat add interface "Ethernet 2"
          netsh routing ip nat set interface "Ethernet 2" mode=full
          netsh routing ip nat add interface "Ethernet 2"

          Restart-Service -Name RemoteAccess
        }
        TestScript = {
          If ((Get-Service -Name RemoteAccess).status -eq 'Stoped') 
          {
            return $false
          }
          else 
          {
            return $true
          }
        }
        GetScript = {

        }          
        DependsOn = '[xComputer]DomainMembership','[WindowsFeature]RSATRemoteAccess', '[WindowsFeature]Routing'
      }
    }
  }

**Comment by iainbrighton** [comment]
@andlo Hmmmm. I've not seen that, but that doesn't mean there isn't a problem. I'll do some testing, but I think a fix for this might have to wait for [xVMNetworkAdapter](https://github.com/PowerShell/xHyper-V/pull/53) to be merged in to resolve properly..

**Comment by iainbrighton** [comment]
@andlo xVMNetworkAdapter has now been merged in v3.7.0.0 👍. Therefore, I can look and have a think about how we can retrofit this into Lability..

**Comment by bneg** [comment]
It's been a while, any updates on this? thanks!

**Comment by iainbrighton** [comment]
Hi @bneg - I did do some testing, but I think this is a Server 2012 R2 problem. When I deploy 2012 R2 VMs, roughly half the time, the NICs are seen by the OS in the incorrect order (they're correct in Hyper-V). When testing with Server 2016 I did not see this behaviour. Have you (or anyone else) seen the same behaviour?

**Comment by MikeShepard** [comment]
I have seen this in 2016.  :-(

**Comment by iainbrighton** [comment]
Grrr - in which case I don't think there's a lot we can do 😭. The order in which the network adapters are listed in the GUI, and via the cmdlets is consistent; it looks like the order in which they are detected in Windows is not 😠.

Perhaps a workaround would be to set the MAC address of each NIC in the Lability configuration and then use the [xNetworkAdapterName](https://github.com/PowerShell/xNetworking/wiki/xNetAdapterName) resource to rename the correct adapter?

**Comment by mrled** [comment]
Hi, just wanted to report that I'm seeing this as well. I'm using Server 2016 for my lab VMs from a Windows 10 Version 1703 Build 15063.966.

Is there a way we can implement the workaround now, or will that require a new version of Lability?

**Comment by iainbrighton** [comment]
The only reliable method I have found thus far is to specify the MAC address of each VM NIC and then use the xNetworking\xNetAdapterName resource to rename the correct adapter using the MAC address. I have uploaded an example [.psd1](https://github.com/VirtualEngine/Lability/blob/dev/Examples/MultipleNetworkExample.psd1) and  [.ps1](https://github.com/VirtualEngine/Lability/blob/dev/Examples/MultipleNetworkExample.ps1).

Another alternative is to use Network Device Naming, but this only works on Windows 10/Server 2016 hosts ___and guests___ - it won't work with a 2012 R2 guest running on Windows 10 1803. In addition, it would require adding functionality to the [xVMNetAdapter](https://github.com/PowerShell/xHyper-V/tree/dev/DSCResources/MSFT_xVMNetworkAdapter) and [(x)NetAdapterName](https://github.com/PowerShell/NetworkingDsc/tree/dev/Modules/NetworkingDsc/DSCResources/MSFT_NetAdapterName) resources.

**Comment by csandfeld** [comment]
Based on my (admittedly very limited) tests, I think we can assume that dynamic mac addresses, are assigned to the NIC’s in the order they are added to the VM. If that assumption holds true, I think the NIC naming can be handled using the Script resource (even if that may not be the most elegant solution) without specifying static mac addresses.

I have created an example here: [SetNetAdapterNames.ps1](https://github.com/csandfeld/DSC_Snippets/blob/master/Snippets/NetAdapter/SetNetAdapterNames.ps1)

Does that seem like a viable approach?

**Comment by iainbrighton** [comment]
Closing as there are two workarounds to the issue. Please reopen if you feel neither are satisfactory solutions. Thanks, Iain
