### ISSUE TITLE
Throws error when downloaded resource checksum is correct 

### ISSUE THREAD

**Issue by christophekumor** [VirtualEngine/Lability#219]
Hello, juts a little problem.
When you download Isos, it throw an error about checksum, even if this one is good
I checked the  iso's checksum and it was good.

i Made more tests (other isos) and each time it's the same, trow error ..

best regards

**Comment by iainbrighton** [comment]
Hi @christophekumor - sorry to hear you're having problems 😭. Can you provide the command and resulting output that you are seeing? It would also be handy to know what version of Lability and PowerShell you're running.
