### ISSUE TITLE
Resolve-ProgramFilesFolder does not return any

### ISSUE THREAD

**Issue by janegilring** [VirtualEngine/Lability#224]
I ran into the following error on Windows 10 (PS Version 5.1.15063.483):
_Install-LabModule -Scope AllUsers -ConfigurationData $LabilityConfigurationData -ModuleType Module
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:48 char:48
 ...     $DestinationPath = Join-Path -Path $localizedProgramFiles -ChildP ...
     CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
Copy-LabModule : Cannot validate argument on parameter 'DestinationPath'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:61 char:24
         Copy-LabModule @copyLabModuleParams_

I tried to run $localizedProgramFiles = Resolve-ProgramFilesFolder -Path $env:SystemRoot manually and noticed that it does not return any output, thus the Install-LabModule function fails.

**Comment by iainbrighton** [comment]
Hi @janegilring - what system locale are you running/deploying for the target VM?

**Comment by janegilring** [comment]
Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1044             nb-NO            Norwegian, Bokmål (Norway)

**Comment by iainbrighton** [comment]
Weird! According to [Google](https://en.wikipedia.org/wiki/Program_Files) the %ProgramFiles% localisation for Norwegian is `Programfiler`, but there are obviously multiple Norwegian localization options as the Resolve-ProgramFilesFolder method is returning nothing!

What is the %ProgramFiles% on your host OS and VM OS?

**Comment by janegilring** [comment]
C:\Program Files

Forgot to inform about UI language:

Get-UICulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

**Comment by iainbrighton** [comment]
@janegilring OK - I've figured out what's wrong and I was off down the wrong path (pun intended!).

For the `-AllUsers` scope it was using the %SYSTEMROOT% environment variable and not %SYSTEMDRIVE%. Obviously, the `Program Files` directory does not exist under `C:\Windows`!

I'll submit a PR to fix it so its in the next release. Thanks for reporting!
