### ISSUE TITLE
GetResourceDownload : A parameter cannot be found that matches parameter name 'ThrowOnError'

### ISSUE THREAD

**Issue by janegilring** [VirtualEngine/Lability#225]
This occured when running Start-LabConfiguration against the built-in NanoExample:

VERBOSE: [08:24:22] Resource 'E:\Lability\ISOs\2016_x64_EN_Eval.iso' does not exist.
GetResourceDownload : A parameter cannot be found that matches parameter name 'ThrowOnError'.
At line:114 char:41
         $resource = GetResourceDownload @PSBoundParameters;

     CategoryInfo          : InvalidArgument: (:) [GetResourceDownload], ParameterBindingException
     FullyQualifiedErrorId : NamedParameterNotFound,GetResourceDownload
 
VERBOSE: [08:29:03] Resource 'E:\Lability\ISOs\2016_x64_EN_Eval.iso' checksum does not match '18A4F00A675B0338F3C7C93C4F131BEB'.
Resource download 'E:\Lability\ISOs\2016_x64_EN_Eval.iso' checksum does not match '18A4F00A675B0338F3C7C93C4F131BEB'.
At line:135 char:13
             throw ($localized.ResourceChecksumMismatchError -f $Desti ...

     CategoryInfo          : OperationStopped: (Resource downlo...7C93C4F131BEB'.:String) [], RuntimeException
     FullyQualifiedErrorId : Resource download 'E:\Lability\ISOs\2016_x64_EN_Eval.iso' checksum does not match '18A4F00A675B0338F3C7C93C4F131BEB'.

When running the command a second time, without any modifications in the mean time, it ran without issues. I understand that this might be difficult to re-produce...maybe a timing issue?

**Comment by iainbrighton** [comment]
@janegilring Is this with the published 0.11.0 version on the Gallery? If so it has been fixed in the [dev branch](https://github.com/VirtualEngine/Lability/commit/63f88ba9d0930e9eb3bc54536b5d4f1b7535cf80). This will be published to gallery soon.

**Comment by janegilring** [comment]
Correct. That`s great :)
