### ISSUE TITLE
SetUnattendXml : Exception calling "Save" with "1" argument(s): "Could not find a part of the path 'G:\Windows\System32\Sysprep\Unattend.xml'."

### ISSUE THREAD

**Issue by rdtechie** [VirtualEngine/Lability#232]
I'm getting the next issue when executing Start-LabConfiguration:

![image](https://user-images.githubusercontent.com/6579452/28527134-ed0e58aa-7089-11e7-8be3-eaa807864227.png)

**Comment by iainbrighton** [comment]
Hi @rdtechie - I can only assume that there is no `C:\Windows\System32\Sysprep` folder. Can you mount the `C:\Lab\VMDiffHardDisks\DC1.vhdx` disk and check?

**Comment by rdtechie** [comment]
Jup, no Sysprep folder.

**Comment by iainbrighton** [comment]
@rdtechie Any chance you can test whether [this commit](https://github.com/iainbrighton/Lability/commit/d48fae580cfd58d8a278584322fd1896d184b618) fixes your problem?

**Comment by rdtechie** [comment]
Still doesn't work, but if I debug it, and create the directory on the vhdx before unattend.xml gets copied, it works. I think there's a step missing. It check and creates other directories, but not the <driveletter>\Windows\System32\Sysprep directory:
![image](https://user-images.githubusercontent.com/6579452/28539330-915cd752-70b1-11e7-9091-9a30a16a1c07.png)

**Comment by iainbrighton** [comment]
@rdtechie Are you sure you're using the right commit? There should be a `Testing target directory 'F:\Windows\System32\Sysprep` debug message shown.

**Comment by rdtechie** [comment]
This one true? https://github.com/iainbrighton/Lability/tree/d48fae580cfd58d8a278584322fd1896d184b618

**Comment by rdtechie** [comment]
With the latest commit it's solved Ian. Thanks!
