### ISSUE TITLE
Applying prefix/suffix to network switch is a breaking change; shouldn't occur if I don't specify a switch in the environment config

### ISSUE THREAD

**Issue by rikhepworth** [VirtualEngine/Lability#236]
Version 0.12.0 applies EnvironmentPrefix to the Lability_SwitchName. Our environments deliberately do not specify the switch name or network in the environment PSD1 so all will use the default switch. The behaviour in v0.12.0 always applies the prefix, even when no switch is specified.

I see this not only as a breaking change, but having though about it, it's counter-intuitive. If I want environments deployed to unique switches I'll specify the name in the environment, at which point the prefix/suffix _should_ logically apply. However, if I _don't_ specify a switch name then the expected behaviour is to use the switch specified in the lab VM defaults. This is not the behaviour in 0.12.0.

This causes issues for us because our default virtual switch is configured with a static IP and a netnat to allow access to external networks via Windows 10 NAT. When lability creates a new switch unexpectedly the associated NIC is not assigned a static IP and the network is not included in the netnat. This breaks our deploys that access resources across the network.

**Comment by iainbrighton** [comment]
@rikhepworth v0.12.1 has been published to the PSGallery and includes a `-DisableSwitchEnvirnonmentName` parameter on the `Set-LabHostDefault` cmdlet. __You should enable this switch to ensure that switch naming is *disabled* (it will be enabled for new installs by default)__.

**Comment by iainbrighton** [comment]
@rikhepworth Correction - v0.12.2 😊.
