### ISSUE TITLE
Wrong variable name in check for Dism version in New-LabImage

### ISSUE THREAD

**Issue by andrekamman** [VirtualEngine/Lability#247]
I have a fresh install of Windows 10 and on it Lability throws an error saying that I need dism version 10.0.0.0
(I have this version installed, it seems the check doesn't see that correctly)
Turns out, Line 69 of New-LabImage checks $labDefaults.version, but I think this should be $labDefaults.DismVersion
I've attached a file with the (small) fix

[New-LabImage.ps1.txt](https://github.com/VirtualEngine/Lability/files/1246245/New-LabImage.ps1.txt)

**Comment by gabrielmccoll** [comment]
Bad timing for me,  first time trying this and trying to learn DSC. Sitting here thinking I'd flunked. 
Great module anyway guys

**Comment by iainbrighton** [comment]
@andrekamman @gabrielmccoll Sorry - been on holiday for a couple of weeks 😢. I'll double-check the unit tests as this should be covered (and obviously isn't).

**Comment by gabrielmccoll** [comment]
That's okay you're doing great work ! Hope you had good holiday

**Comment by gabrielmccoll** [comment]
What a guy. Like I said on other thread if I can help out am happy to do so
