### ISSUE TITLE
HyperV Switch Name gets Doubled EnvironmentPrefix

### ISSUE THREAD

**Issue by jrdnr** [VirtualEngine/Lability#251]
I'm trying to build a very basic 3 node domain lab based off of the Example\TestLabGuide.ps1.  However when I run `Start-LabConfiguration ...` where the EnvironmentPrefix = 'TLG-', Lability creates the HyperV network "TLG-TLG-Corpnet", which caused the Lab build to error out since it cannot build the VM's w/o the specified Network.  

[Work Around] - To get around this issue I've just manually created a 'TLG-Corpnet' switch and then the vms build fine.  However I'm left with the "TLG-TLG-Corpnet" switch being created every time I try to fire off a lab build.

**Comment by iainbrighton** [comment]
@jrdnr Hmmm - I can see this happening and will investigate why. Thanks for reporting.
