### ISSUE TITLE
PSDesiredStateConfiguration download error

### ISSUE THREAD

**Issue by hektop** [VirtualEngine/Lability#253]
When I try to run nanoExample.ps1 I get the following error. I've been doing Lability for a while now but I had to reload my laptop and start all over again. It seems that PSDesiredStateConfiguration version 1.1 is no longer in the powershell gallery. Is there a work around to make Lability to work? I managed to get the zip file but I am not sure in which directory I need to place in order for the script to pick it up and not download it from the powershell gallery.

VERBOSE: [3:40:26 PM] Module 'PSDesiredStateConfiguration' v1.1 was not found in the module cache or -Force was specified.
VERBOSE: [3:40:26 PM] Downloading resource 'https://www.powershellgallery.com/api/v2/package/PSDesiredStateConfiguration/1.1' to 'C:\ProgramData\Lability\Modules\PSDesiredStateConfiguration.zip'.
VERBOSE: [3:40:26 PM] Dismounting disk image 'C:\Users\Hector.Andrade\Lability\VMVirtualHardDisks\LON-DC01.vhdx'.
Error: 9/27/2017 3:40:27 PM:
 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Web resource 'https://www.powershellgallery.com/api/v2/package/PSDesiredStateConfiguration/1.1' download failed.

**Comment by iainbrighton** [comment]
Hi @hektop - thanks for reporting. I don't think that the `PSDesiredStateConfiguration` module has ever been published in the gallery?! Should this be the `xPSDesiredStateConfiguration` module? Can you post the Lability .psd1 configuration file?

**Comment by hektop** [comment]
Here is the Lability.psd1 file

[Lability.zip](https://github.com/VirtualEngine/Lability/files/1341037/Lability.zip)

**Comment by hektop** [comment]
I just noticed that you wanted my .psd1 configuration file not the Lability.psd1 file I sent. I went and checked and saw that I had the following line of code inside DSCResource in the NonNodeData. I removed this line of code and that fixed my issue. Wow this was a newbie mistake, thanks for pointing that out.

```@{ Name = 'PSDesiredStateConfiguration'; RequiredVersion = '1.1'; }```

**Comment by iainbrighton** [comment]
Correct - That's a built-in resource that cannot be downloaded 😉. Glad you're all sorted now!
