### ISSUE TITLE
Question: Windows Server 2008 support?

### ISSUE THREAD

**Issue by codykonior** [VirtualEngine/Lability#257]
Is it difficult to add Windows Server 2008 support (baking WMF 5/5.1 into it for the DSC components)?

**Comment by iainbrighton** [comment]
Hi @codykonior sure, but you'll need to register your own media. Check out the [2008R2_x64_Standard_EN_Eval](https://github.com/VirtualEngine/Lability/blob/dev/Examples/CustomMedia.psd1) example and just remember to install WMF 5.x before SYSPREPing the VM 😃.
