### ISSUE TITLE
error enabling guest integration service on non-english Hyper-V host

### ISSUE THREAD

**Issue by carfesh** [VirtualEngine/Lability#270]
On a German (probably any non-English OS) Hyper-V host, enabling the guest integration service will fail. The name passed to Enable-VMIntegrationService seems to be language specific.

The German equivalent of "Guest Service Interface" is "Gastdienstschnittstelle".

The following screenshot shows the error that is thrown in the Lability xHyper-V DSC resource.

![2017-11-21 14_40_35-administrator_ windows powershell](https://user-images.githubusercontent.com/16491101/33075501-fc8cc7dc-cec9-11e7-89b0-b7b2737bbf38.png)

This screenshot shows a list of available integration services:

![2017-11-21 14_39_28-administrator_ windows powershell](https://user-images.githubusercontent.com/16491101/33075456-d152e574-cec9-11e7-9f66-d2b7a9f84abf.png)

I could not find any language independent alternative yet.

**Comment by iainbrighton** [comment]
Hi @carfesh - this is [apparently fixed](https://github.com/PowerShell/xHyper-V/issues/73) in the latest xHyper-V release.

_Would you mind testing this on your system by replacing the bundled `.\Lability\DSCResources\xHyper-V\DSCResources\MSFT_xVMHyperV\MSFT_xVMHyperV.psm1` implementation with the [v3.7.0.0 xVMHyperV](https://github.com/PowerShell/xHyper-V/blob/dev/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1) code containing this fix?_

If this fixes it, we can look at replacing the bundled xVMHyperV implementation. Ideally, we'd wait for https://github.com/PowerShell/xHyper-V/pull/124 to be merged so we can update the whole xHyper-V module, but this looks a little way off and is waiting for me 😢. 

Thanks, Iain

**Comment by carfesh** [comment]
Hi Iain,

interesting, and a great example of where Lability benefits from development around PowerShell DSC.

I could test it successfully, the fixed version works fine for me. I'll probably create my own custom Lability installer in NSIS for the time being, as I need to deploy the fixed version to multiple hosts.

I'm still working on getting my first lab up and running; I used the AutomatedLab framework in the past, but I like how simple and elegant lab setup is in Lability if the required DSC resources are available. 

Great work, and thanks a lot for your effort!

Best regards,
  Torsten

**Comment by iainbrighton** [comment]
That was the idea - any development for Lability should be pushed upstream to the corresponding DSC resource 😃.

I'll leave this issue open until the xVMHardDiskDrive and xVMSCSIController resources have been merged and I've updated the bundled module.

**Comment by iainbrighton** [comment]
@carfesh Thanks for your patience. Version 0.13.0 has been released to the gallery that includes the xHyper-V fix. Let me know if this doesn't fix things for you 😄.
