### ISSUE TITLE
MaxEnvelopeSizeKb too low and cannot be increased

### ISSUE THREAD

**Issue by Rokory** [VirtualEngine/Lability#282]
Hi guys,

first of all thank you for this fantastic work, which saved me a lot of time already.

However, I am running in an issue on one machine, that the MaxEnvelopeSizeKb parameter is too low. I noticed that in the default bootstrap it is set zu 1 MB, which is not sufficient for my demand. Moreover, it seems that there is no way to increase that without directly editing the original file, which I do not want to.

Suggestion:

Before setting this to 1 MB, check if it is at least 1 MB, so we can customize this parameter using a custom bootstrap injection.

**Comment by iainbrighton** [comment]
Hi @Rokory, glad you find it useful 😃. We can look at adding a new setting to the `Set-LabVMDefault` cmdlet. This will allow you define it globally for all VMs and/or override it in your configuration data. Do you think this ould this work for you?
