### ISSUE TITLE
New Issue with ScriptHalted

### ISSUE THREAD

**Issue by quizard** [VirtualEngine/Lability#299]
![image](https://user-images.githubusercontent.com/9592605/40868843-785b00e8-65df-11e8-999f-02686a70a181.png)

I'm seeing this issue on a new machine even when trying to use the stock examples.  Both machines using .0.14.0. New machine is stock SRV 2016. Virtual machines never get created. Clean machine and unsure how to troubleshoot. Hoping someone can point me in the right direction. Thank you!

PowerShell 5.1
Microsoft Windows [Version 10.0.14393]
Lability 0.14.0

**Comment by iainbrighton** [comment]
Hi @quizard thanks for reporting. I think this is the same as #294. Is there any chance you can download the dev branch and try that?

**Comment by quizard** [comment]
Will do! Thank you for the quick response and great work!

**Comment by quizard** [comment]
Ack.. I should have tried that first! I'm building again, thank you!!!

**Comment by iainbrighton** [comment]
@quizard Did that work? If so, I'll get the latest dev branch published to the gallery!

**Comment by iainbrighton** [comment]
@quizard Version 0.15.0 has now been released to the PowerShell Gallery 😄.
