### ISSUE TITLE
Request for Help

### ISSUE THREAD

**Issue by Paddylabs** [VirtualEngine/Lability#300]
Would anyone know where I could find some tutorials or help regarding using lability with Ravello? I have tried searching but I'm drawing a blank.

**Comment by iainbrighton** [comment]
@Paddylabs I don't think Lability will help you here 😞. Lability will read an existing DSC configuration document (.psd1) and provision local VMs, but only on Hyper-V.

We use Ravello internally, but have to manually push DSC configurations when creating a new blueprint, i.e. treat the nested VMs like they are existing/physical machines.

**Comment by Paddylabs** [comment]
Thank you for the info, sorry for the slow reply!
