### ISSUE TITLE
lability fails at Testing 'Test-VMTargetResource' failed.

### ISSUE THREAD

**Issue by zachattac** [VirtualEngine/Lability#301]
Hi All I am pulling my hair out, I am trying to fault find, I cant get past 
'Test-VMTargetResource' failed.
I get this warning
WARNING: [3:55:54 PM] DSC resource 'Test-VHDTargetResource' failed with errror 'Specify MaximumSizeBytes property for
Fixed and Dynamic VHDs.'.
Where is this set in the config files?
cheers Dene

**Comment by iainbrighton** [comment]
@zachattac I guess you're running on a pre 1709 release? If so, this is fixed in the latest dev branch, but I will publish this to the gallery today.

**Comment by iainbrighton** [comment]
@zachattac Version 0.15.0 has been released to the PowerShell Gallery. This should resolve your issue - please reopen this issue if it does not.

**Comment by zachattac** [comment]
Thanks Iain much appreciated I'll give it a try in the morning.
cheers Dene

**Comment by zachattac** [comment]
Hi Iain, I am getting there, it now fails when creating the VM, if I create the VM manually then Lability will finish. Cheers Dene

VERBOSE: [11:48:24 AM] Finished Lab configuration test.
VERBOSE: [11:48:24 AM] Node 'NANO1' is missing or misconfigured.
VERBOSE: [11:48:24 AM] Creating VM 'NANO1'.
VERBOSE: [11:48:24 AM] Setting Virtual Switch configuration 'Internal'.
WARNING: [11:48:24 AM] Using existing 'Internal' virtual switch.
VERBOSE: [11:48:25 AM] (Re)setting VHDX configuration 'NANO1.vhdx'.
VERBOSE: [11:48:25 AM] Testing 'Test-VHDTargetResource' failed.
VERBOSE: [11:48:26 AM] Setting VM configuration 'NANO1'.
VERBOSE: [11:48:26 AM] Creating Gen 2 virtual machine.
VERBOSE: [11:48:26 AM] Importing bundled DSC Resource 'xHyper-V\MSFT_xVMHyperV'.
VERBOSE: [11:48:26 AM] Testing 'Test-VMTargetResource' failed.
New-VM : Failed to create a new virtual machine.
'NANO1' failed to realize. (Virtual machine ID 107A36B2-2091-47B8-99F2-278B6132D5F8)
Failed to access configuration store: The system cannot find the path specified. (0x80070003).
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.15.0\DSCResources\xHyper-V\DSCResources\MSFT_xVMHyperV\MSFT_xV
MHyperV.psm1:481 char:21
+             $null = New-VM @parameters
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.NewVM

Set-VM : Hyper-V was unable to find a virtual machine with name "NANO1".
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.15.0\DSCResources\xHyper-V\DSCResources\MSFT_xVMHyperV\MSFT_xV
MHyperV.psm1:517 char:21
+             $null = Set-VM @parameters
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVM

**Comment by iainbrighton** [comment]
@zachattac This looks like a Hyper-V problem (or at least a problem with the xHyper-V DSC resource). What OS version are you running?

**Comment by zachattac** [comment]
Hi Iain, I am running Windows 10
BuildNumber     : 16299
Version         : 10.0.16299

and Powershell
PSVersion                      5.1.16299.492
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.492
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

If I manually create the VM and rerun it will finish.
thanks again cheers Dene

**Comment by iainbrighton** [comment]
This looks like a Hyper-V/PowerShell cmdlet issue although the error message implies that the VM configuration path is inaccessible.

Can you try changing the VirtualMachinePath to another location and resetting it back again (as per https://www.reddit.com/r/HyperV/comments/56g0nq/failed_to_create_a_vm/) or disabling and enabling the Hyper-V feature?

**Comment by iainbrighton** [comment]
@zachattac Is this still a problem? Have you tried disabling the Hyper-V feature with `Disable-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All`, rebooting and then re-enabling?

**Comment by zachattac** [comment]
Hi Iain, no I haven't tried that , I have been concentrating on my labs,
you can close it and I will try it at a later time when I have completed my
certs.
thanks for you help.
cheers Dene

**Comment by iainbrighton** [comment]
@zachattac no problem. It definitely looks to be something Hyper-V/PowerShell related. Please open another issue if you try enabling/disabling the Hyper-V feature and you still have the problem.
