### ISSUE TITLE
How to Troubleshoot

### ISSUE THREAD

**Issue by Paddylabs** [VirtualEngine/Lability#312]
Hi,

I'm having an issue where I've copied one of the example labs and edited it to create a lab scenario I need.  When I go to deploy the lab the MOF generate ok but when I start the Lab there is a base disk image for each VM in the lab, a differencing disk for each VM and each differencing disk is increasing in size and is being written to but the VM never boot.  The ISOs are local so I don't know whats happening.

So two questions really.  Does any one know what's happening to my lab here OR does anyone know where or what I can use to troubleshoot this?

**Comment by ChrisLGardner** [comment]
My usual step when troubleshooting labs is to shutdown/stop the VM and then start it again. This should boot into windows and let you log in, from there look in C:\Bootstrap and there should be a log file for you to look through. Hopefully that has some information in it that will help, if the disk is increasing in size then that is probably filling up with one or two errors as DSC keeps rerunning and hitting the same problems.

**Comment by Paddylabs** [comment]
Oh you utter star. Damn.. I wasted a few hours last night reading up trying to figure that out! Didn't think about stopping and starting the VM to get into windows.

The error in the log is:-

The PowershellDSC resource MSFT_xIPAddress from Module <xNetworking,5.6.0.0> does not exist at the Powershell module path nor is registered as a WMI DSC resource.

**Comment by ChrisLGardner** [comment]
Sounds like your DSC config is referencing that version but the environment psd1 is referencing a different version (or no version). 

The simple solution is to make sure they match, I'd favour what is stated in the DSC config over what is in the psd1 and update the psd1 to the correct value. Once you've done that you should be able to remove the lab and redeploy it and hopefully it'll work.

Which config example are you using?

**Comment by Paddylabs** [comment]
I am using the TestLabGuide.  I've just found where it says required version and not minimum version (along with a million other people asking the same thing).  Noob mistake but thank you so much for helping me out, I was getting disheartened!

**Comment by iainbrighton** [comment]
@Paddylabs this is the most common problem with Lability - although it's actually a DSC issue. *You have to make sure Lability copies the version of resources that the .mof file requires.* 

Using the `RequiredVersion` helps, but only if you generate the .mof file using the same version! Lability does do some checking and will warn you if it detects a mismatch between the Lability configuration (.psd1) and the .mof file:
```powershell
WARNING: [1:55:50 PM] Module 'xNetworking' definition is configured with the 'MinimumVersion' property. It is recommended to use the 'RequiredVersion' property instead.
WARNING: [1:55:50 PM] Module 'xNetworking' version mismatch. The version '5.7.0.0' defined in the .mof file does not match the version '2.7.0.0' defined in the Lability configuration file.
```
