### ISSUE TITLE
Computername not too long

### ISSUE THREAD

**Issue by Rokory** [VirtualEngine/Lability#314]
https://github.com/VirtualEngine/Lability/blob/8c890e085068dc211fd1557ce527024cf0d35edb/Src/Private/New-LabVirtualMachine.ps1#L63

I think this line should test $nodename instead of $displayName. $displayName is prefixed with an environment-prefix and is the name of the VM. VM names with more than 15 characters are allowed and do not cause any problems. Only the internal computername of the VM should be 15 characters max.

**Comment by iainbrighton** [comment]
Hi @Rokory - I think you are right! I will look at fixing this - Thanks Iain
