### ISSUE TITLE
Custom resource ZIPs with expand are not recursive?

### ISSUE THREAD

**Issue by codykonior** [VirtualEngine/Lability#321]
Windows Server comes with NET 3.5 removed and to add it as a feature you need the sources\sxs folder from the ISO.

I wrote some code into my build scripts to mount the ISO in the same way Lability does, Compress-Archive the contents, and then I have a custom resource:

```
                @{
                    Id              = 'Net-Framework-Core'
                    Filename        = '..\Resources\Net-Framework-Core.zip'
                    Expand          = $true

                    IsLocal         = $true
                }
```

But sadly it seems that the method that decompresses archives ignores all of the subdirectories and tries to put everything into one folder :-/ So you get a bunch of warnings that everything is overwriting everything else.

I can extract the entire Server ISO into the folder (instead which I think I'll have to) but I just wanted to know if this is intentional.

**Comment by iainbrighton** [comment]
@codykonior Hmmm - this should work. Do you have an example ZIP file hosted anywhere that I can experiment with?

**Comment by iainbrighton** [comment]
@codykonior Also - .NET 3.5 is installed in all base Lability images. You will see this feature included in the `\config\media.json` file.
```json
"CustomData":  {
    "WindowsOptionalFeature":  ["NetFx3"]
}
```
Are you using your own ISO or WIM media files? If so, you could also get Lability to install .NET 3.5 during VHD creation.

**Comment by codykonior** [comment]
I have a CustomMedia for Server 2012 based on the Evaluation ISO. I switched to using WindowsOptionalFeature for this one and that works great, so I'm done thanks.
