### ISSUE TITLE
Looking to help

### ISSUE THREAD

**Issue by tigerfansga** [VirtualEngine/Lability#322]
I found an issue with a link in the README.md. I don't mind correcting and issuing a pull requests but there  are not contributing guidelines, and I didn't want to just issue a random pull request. Plus I wasn't sure what branch to checkout for such a change.

**Comment by iainbrighton** [comment]
Hi @tigerfansga ironically there is an issue to create the contribution guidelines! Until then, please send in the PR with the updates 😄.

**Comment by tigerfansga** [comment]
Great @iainbrighton, I will get a PR submitted later today.
