### ISSUE TITLE
Add in Server 2019 Media options

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#323]
As Server 2019 was released recently it would be good to have 2019 available as a usable image in the Media.json file

**Comment by kilasuit** [comment]
this could be an easy win for Hacktoberfest

**Comment by iainbrighton** [comment]
@kilasuit Yep - once the evaluation downloads are available here: https://www.microsoft.com/en-GB/evalcenter/

**Comment by janegilring** [comment]
It seems the eval version was published yesterday - available [here](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019).

**Comment by iainbrighton** [comment]
@janegilring Awesome - I have been checking periodically. I shall add the 2019 media into the next release (will be in the next day or two!).
