### ISSUE TITLE
Changing a switch type ends in obscure error message

### ISSUE THREAD

**Issue by codykonior** [VirtualEngine/Lability#326]
```
    NonNodeData = @{
        Lability = @{
            Network     = @(
                @{ Name = 'CHICAGO'; Type = 'Internal'; }
                @{ Name = 'SEATTLE'; Type = 'Internal'; }
                @{ Name = 'SEATTLE_HB'; Type = 'Internal'; }
                @{ Name = 'DALLAS'; Type = 'Internal'; }
                @{ Name = 'DALLAS_HB'; Type = 'Internal'; }
            )
```

If you build this, and then build it again after changing SEATTLE_HB and DALLAS_HB to Private, you'll get these warnings during build:

```
WARNING: [1:51:28 AM] DSC resource 'Set-VMTargetResource' failed with errror 'Sequence contains more than one element'.
```

It seems that Hyper-V creates duplicate switches, but then can't decide which one to use and so doesn't attach it to the VM.

Totally fine with this not being fixed but even with -Verbose it took a while to find the cause. So some better error message would be great. Unless it's already documented somewhere.

**Comment by iainbrighton** [comment]
Hi @codykonior - this error message is generated by the [xVMSwitch](https://github.com/PowerShell/xHyper-V/blob/dev/DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1) DSC resource. Ideally it should be fixed there as Lability just bundles the Hyper-V DSC resources. Would you mind logging the issue in the [xHyper-V repository](https://github.com/PowerShell/xHyper-V/issues) and reference this issue?

**Comment by codykonior** [comment]
I was going to do this but I was having trouble finding that error message in the xVMSwitch code.
