### ISSUE TITLE
@absolutejam link broken in readme.md

### ISSUE THREAD

**Issue by Stupastian** [VirtualEngine/Lability#332]
I guess that's all, "The Ultimate Hyper-V Lab Tool via @absolutejam" has been giving 404 for a while now.

**Comment by iainbrighton** [comment]
I have sent @absolutejam a DM on Slack and hopefully, he'll respond at some point

**Comment by Stupastian** [comment]
Thanks for the Way Back Machine and update!

**Comment by iainbrighton** [comment]
Closing out as I cannot get hold of @absolutejam 😢. I'll update the link with the web.archive.org link.
