### ISSUE TITLE
Failing v4 test

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#336]
Unit test `Converts custom media from a JSON file/Uri` fails periodically on the v4 build agents and has been temporarily disabled. This needs fixing and re-enabling.

**Comment by iainbrighton** [comment]
I think that moving the test .json file to the %TEMP% directory (away from Pester's $TestDrive) will mean that Pester can successfully test down the test drive even if the file handle has not been closed.

**Comment by csandfeld** [comment]
Another (perhaps less elegant) solution might be to mock Invoke-RestMethod

**Comment by csandfeld** [comment]
Something like

```PowerShell
$customMedia = @'
{
    "Id": "LabilityCustomMediaTest",
    "Filename": "WIN10_x64_ENT_RS4_EN_Eval.iso",
    "Description": "Windows 10 64bit Enterprise 1804 English Evaluation",
    "Architecture": "x64",
    "ImageName": "Windows 10 Enterprise Evaluation",
    "MediaType": "ISO",
    "OperatingSystem": "Windows",
    "Uri": "https://software-download.microsoft.com/download/pr/17134.1.180410-1804.rs4_release_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso",
    "Checksum": "89F6B3079B3669560D29F3C4BE9CC74D"
}
'@

Mock Invoke-RestMethod { $customMedia | ConvertFrom-Json }
```

**Comment by iainbrighton** [comment]
Do you think that it's IWR holding the file handle open?

**Comment by csandfeld** [comment]
Not sure, but figured we would not need to touch the filesystem, if we mock that command.
