### ISSUE TITLE
Setting injection drive letter

### ISSUE THREAD

**Issue by regularroutine** [VirtualEngine/Lability#337]
Hey,
How do I set the default drive for injecting the mof, bootstrap etc? My setting seem to be E and I cannot fin where to change this:

VERBOSE: [11:48:35] Adding VM resources.
VERBOSE: [11:48:35] Adding BootStrap.ps1 file to 'E:\BootStrap'.
VERBOSE: [11:48:35] Creating directory 'E:\BootStrap'.

Thanks,
David

**Comment by csandfeld** [comment]
Hi David,

That drive letter is determined automatically when Lability mounts the differencing disk for the individual VM's, in order to inject the bootstrap files. I don't think there is anywhere to change that.

**Comment by iainbrighton** [comment]
Hi @regularroutine - @csandfeld is right. The drive letter is assigned when the VHD is mounted. What are you trying to achieve that fixing the drive letter would hope to achieve?

**Comment by regularroutine** [comment]
Thanks guys. I am brand new to lability. I am trying to get the mof file to be configured when the vm boots up. Do I have to add another drive to all vms?
Thanks

**Comment by iainbrighton** [comment]
You need to generate the .mof and .meta.mof files outside of Lability. If you put them in the %LabilityConfigurationPath% ($env:LabilityConfigurationPath) it will inject them for you. You can override the path if you want when running  `Start-LabConfiguration` with the `-Path` parameter, e.g. `Start-LabConfiguration -ConfigurationData .\MyPsd1File.psd1 -Path .\MyMofFiles`

**Comment by regularroutine** [comment]
Happy new year! I understand now: the referenced E drive is the drive that is mounted to my hyperv host whilst bootstrapping the files! 
My Mof files are boostrapped and gets configured when using the -Path variable.

Thanks a lot for the clarification. Very powerful stuff!

**Comment by iainbrighton** [comment]
You're welcome! If you have any more questions, please open another issue.
