### ISSUE TITLE
Suggestion: Make New-LabVM functions MediaId parameter optional

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lability#356]
I suggest making the MediaId parameter of New-LabVM optional, defaulting to the value of the Media property returned by Get-LabVMDefault.

I'm not sure if this would have any unforeseen consequences, but I have implemented it in a separate branch, and it works there (well, it works on my machine). Running the Pester tests only return one failing test, that also failed before I made the change (Get-LabHostConfiguration.ps1 fails PSScriptAnalyzer Linting) so I expect that to be unrelated to the change I made.

Thoughts @iainbrighton

**Comment by iainbrighton** [comment]
@csandfeld I can't see how this will break anything as `New-LabVM` is just for creating ad-hoc VMs!

**Comment by iainbrighton** [comment]
Closed in PR #359
