### ISSUE TITLE
Cache gets updated for DSC modules but not for other modules

### ISSUE THREAD

**Issue by codykonior** [VirtualEngine/Lability#367]
I noticed today that a lot of modules in my VMs were out of date.

I had a look at (Get-LabHostdefault).ModuleCachePath and can see that there's lots of versions of each of the DSC Resource modules, but not of the other modules.

The way I specify the DSC Resource modules is like:

![image](https://user-images.githubusercontent.com/12396330/59654190-bc965900-91c7-11e9-80e0-5a45288e0652.png)

Compared to:

![image](https://user-images.githubusercontent.com/12396330/59654194-c324d080-91c7-11e9-83b8-4fad0e3d171f.png)

I had assumed with just a Name that it would download the latest version but it seems it doesn't. What sucks about this is that Lability knows what version the module is because when it stores it in the cache it also fills out the version number in the filename.

![image](https://user-images.githubusercontent.com/12396330/59654237-ef405180-91c7-11e9-8e59-5c51dbcece2f.png)

Workarounds I can imagine are:
- Always specify the required version with these other modules also (annoying).
- Clear the lab module cache every time with Clear-LabModuleCache (pretty harsh).
- Maybe add another flag to these DSCResource/Modules sections (like Latest = $true) so for PSGallery it gets the latest version number, and downloads if there's a newer one?

Did I miss anything?

Thanks

**Comment by iainbrighton** [comment]
Hi @codykonior - for the DSC resources you will definitely want to specify the `RequiredVersion` property. The DSC resource versions are tied to the MOFs and __not__ specifying the `RequiredVersion` will lead to more problems than it solves.

The internal logic says:
* if there is no version specified and nothing is cached, download the latest version from the gallery
* if there is no version specified and one is already cached, use that

You can force an update of the modules by using the `Invoke-LabResourceDownload` function with the `-Force` switch. If the modules haven't been updated then it will download them again, but if a newer version is available (and no explicit version information is specified) then it'll download the latest version. Therefore, you could run this before starting the lab configuration:
```powershell
Invoke-LabResourceDownload -ConfigurationData $config -Modules -Force
```
Does this work? Thx, Iain

**Comment by codykonior** [comment]
The problem is with the non-DSC modules. 

I need to keep updating those version numbers every time a module is released when it would be easier if it just downloaded the latest. Which is why I'd like a flag on there to say whether the latest is needed or not.

I could purge the entire module cache every time a lab is built but I thought this would be generally useful.

**Comment by iainbrighton** [comment]
If you remove the version numbers from the `Modules = @()` section in the configuration, when you run `Invoke-LabResourceDownload -ConfigurationData $config -Modules -Force` it will download all the latest versions of the modules defined in the configuration data.

Having said that, it will attempt to download the latest versions of __all__ modules, not just selected modules. Being able to indicate individual modules or not having to remember to run `Invoke-LabResourceDownload` could be handy!
