### ISSUE TITLE
Setting SecureBoot value per CustomMedia

### ISSUE THREAD

**Issue by OsaPL** [VirtualEngine/Lability#376]
Hi,
the problem I'm facing is that each time my team would want to use a Win7 images you have to set `SecureBoot = $false` inside `Node`
That means that every, single node would have to use this param which is not ideal (we have a single whole server dedicated to only this task).

Can you somehow set SecureBoot inside CustomMedia? 
(I've seen `Media\CustomData` but I don't see any way to set it there)

**Comment by OsaPL** [comment]
Just to add, I've tried to change to Gen 1, `CustomData = @{ VmGeneration = 1;}` still creates a Gen 2 machine on my PC.

**Comment by OsaPL** [comment]
Yeah, just tested and Gen1 is not also not working.

**Comment by iainbrighton** [comment]
Hi @OsaPL - can you post your custom media definition so we can take a look?

**Comment by OsaPL** [comment]
```@{
    Id = 'Windows7TestGen1';
    Filename = 'en_windows_7_professional_with_sp1_x64_dvd_u_676939.iso';
    Architecture = 'x64';
    Uri = 'file://C:\Lability\ISOs\en_windows_7_professional_with_sp1_x64_dvd_u_676939.iso';
    Checksum = '';
    Description = 'Windows 7';
    MediaType = 'ISO';
    ImageName = '1';
    OperatingSystem = 'Windows';
	CustomData = @{
	  VmGeneration = 1;
	  CustomBootstrap = @(
		'## Unattend.xml will set the Administrator password, but it wont enable the account on client OSes'
		'NET USER Administrator /active:yes;'
		'## This enables guest SMB sessions'
		'$path = "HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation"'
		'if(!(Test-Path $path)){'
		'New-Item $path -Force;'
		'}'
		'Set-ItemProperty $path  -Name AllowInsecureGuestAuth -Value 1 -Force'
		'Set-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell -Name ExecutionPolicy -Value RemoteSigned -Force; #306'
		'## Kick-start PowerShell remoting on clients to permit applying DSC configurations'
		'Enable-PSRemoting -SkipNetworkProfileCheck -Force'
	  );
	}
}

```
Its stuck on "Starting windows..."

**Comment by iainbrighton** [comment]
Unfortunately, you can't use Lability to build directly from a Windows 7 ISO (only PowerShell v2.0 and no DSC). You'll need to use a custom SYSPREP'd VHD/WIM with WMF 4 (or later installed) to get it to work. Does this make sense?

**Comment by OsaPL** [comment]
Yeah, is WMF4 the only prereq for a Lability supported MasterImage?

**Comment by iainbrighton** [comment]
@OsaPL Yes - there is a recommended hotfix too but you can find the [details here](https://github.com/VirtualEngine/Lability/blob/dev/en-US/about_Media.help.txt#L87)

**Comment by iainbrighton** [comment]
@OsaPL Yes - please open a new issue with the details of the issues you're facing in the appropriate repository!
