### ISSUE TITLE
New Release with Updated Media

### ISSUE THREAD

**Issue by jdhitsolutions** [VirtualEngine/Lability#390]
Is it possible to publish a new release to the PowerShell Gallery so we can have the updated media.json file? The published version uses Windows 10 1909 and the file in the repo has 20H1. I'd rather not try to update the file separately.

**Comment by iainbrighton** [comment]
Hi Jeff, the new 0.20.0 release should be in the PSGallery with both 20H1 and 20H2 media! Thanks, Iain
