### ISSUE TITLE
Add Tag/Prefix Support

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#43]
It was mentioned to me in passing that it would be handy to tag/prefix all resources in a configuration (.psd1) to easily to be able to distinguish individual lab environments, i.e. VMs, switches and disks. This is particularly true, if multiple lab environments contain VMs with the same name. How this is implemented is up for discussion!

It's also a shame that standalone Hyper-V doesn't support folders for VM resources :cry:

**Comment by csandfeld** [comment]
I remember asking about that very thing after your presentation at PSSummitEU, nice to see it come up here :smile: 

We could add a "EnvironmentPrefix " (or some other name) parameter to the NonNodeData like so:

```PowerShell
@{
    NonNodeData = @{
        VirtualEngineLab = @{
            EnvironmentPrefix = 'Lab01'
        }
    }
}
```

Then if a prefix is specified, simply prepend that to the name of the VM's and disks when creating them.

Personaly I don't think it would make sense to use the prefix for switches, as you might want to use existing switches, and if not, you could easily create switches with specific names for your lab anyway.

So in a configuration with a node called WIN10CLIENT, if we had the prefix 'Lab01' in the config,  we could just slap that on and name the VM 'Lab01-WIN10CLIENT', and same thing goes for the disks. If no prefix was specified, it would just be business as usual.

Am I way of here, or is it somewhat along the lines of what you had in mind @iainbrighton ?

**Comment by iainbrighton** [comment]
My thinking here is that if you wanted to prefix a lab environment, it is because you want to deploy multiple instances of a lab? For example, a development, a test and/or a production environment. If you don't need to deploy multiple instances then you can add the prefix to each VM and switch as needed directly to the configuration file.

Do I have this correct or are you wanting to use the tags/prefixes for a different purpose?

**Comment by csandfeld** [comment]
My thoughts where more just a way to logically group VM's belonging to the same lab environment. Might be a setup to test SharePoint, another to test CRM, etc, while still allowing the VM hostnames and IP addresses to be the same in several lab environments. Some labs might share the same switch, other would have a switch dedicated for that lab. That's why I suggested keeping the switch out of it.

I do see where you are coming from though (providing I am correctly interpreting what you are saying). Having the ability to create several versions of a lab from a single config file would be sweet as well. For that a solution could be a parameter for the Start-LabConfiguration, Start-Lab and Stop-Lab functions, thus keeping the tag/prefix out of the configuration files.

**Comment by iainbrighton** [comment]
@csandfeld I see where you're coming from - it's just a way of easily identifying VMs in a particular lab environment? Adding a prefix such as `EnvironmentPrefix`, `Prefix` or `LabName` should be fairly straight-forward.

I've picked on `LabName` as I think we could do with a way of identifying lab configurations anyway. This will certainly be needed in the future. Whether this is related to 'prefix' is up for debate.

If we combine the `Prefix` with a parameter on `*-LabConfiguration` cmdlets, we could end up with some interesting combinations of VM, VHDX and switch names! That's another issue and this issue should concentrate on the prefix/identification requirement.

Therefore, what configuration data key/name do we want for:
* The lab name and/or description
 * I would like to make this mandatory, but can't see how we can do this as we _need_ to support a configuration document that has _no_ metadata!
 * This will probably be required when we expand into provisioning on AWS and Azure. However, these 'plugins' might require their own cmdlets anyway.
* The lab prefix
 * Will only apply to the VM display name and the VHDX file (not switches)
 * You might want/need a shorter lab/environment prefix?

__NOTE: we are going to have an impending module rename that will require changing all `VirtualEngineLab = @{}` and `VirtualEngineLab_` entries to the new (whatever that is) module name.__
