### ISSUE TITLE
Environment variables not expanded when running New-LabVM

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lability#55]
On a system with default settings:

```PowerShell
D:\Lability> Get-LabHostDefault


ConfigurationPath       : %SYSTEMDRIVE%\Lability\Configurations
DifferencingVhdPath     : %SYSTEMDRIVE%\Lability\VMVirtualHardDisks
HotfixPath              : %SYSTEMDRIVE%\Lability\Hotfixes
IsoPath                 : %SYSTEMDRIVE%\Lability\ISOs
ParentVhdPath           : %SYSTEMDRIVE%\Lability\MasterVirtualHardDisks
ResourcePath            : %SYSTEMDRIVE%\Lability\Resources
ResourceShareName       : Resources
UpdatePath              : 
DisableLocalFileCaching : False
```

ISO file is downloaded to a path under current directory named "%SYSTEMDRIVE%\Lability\ISOs". Similar issue to the one reported in #33

**Comment by csandfeld** [comment]
Working to fix this now ... will create pull request shortly

**Comment by iainbrighton** [comment]
Excellent! It sounds like it should go in the GetConfigurationData method? Just enumerate all the values and expand any environment variables before returning? That should catch all calls that read the host/VM defaults.

**Comment by csandfeld** [comment]
Argh ... why didn't I think of that. Have been adding ResolvePathEx wherever I found "-Path $hostDefaults..."

**Comment by iainbrighton** [comment]
;)
