### ISSUE TITLE
Add Export/Import configuration cmdlets

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#65]
When testing on multiple machines or rebuilding a machine, the Lability configuration can be captured by copying the files out of the %ProgramData%\Lability\Config folder and restoring them. I think it would be handy to be able to export and import the `CustomMedia.json`, `HostDefaults.json` and `VmDefaults.json` files as a single file.

I'm thinking `Export-LabHostConfiguration` and `Import-LabHostConfiguration` cmdlets would cover this off nicely!

**Comment by csandfeld** [comment]
Sounds like a good idea. Might it make sense to include all data from under %ProgramData%\Lability, in case someone had opted to use custom certificates, and to handle any future config files etc. that might find it's way to this module? Or are you more inclined to just stick with the config files?

Let me know what you think - and if you want me to, I can take a stab at it.

**Comment by iainbrighton** [comment]
v0.9.7 only does the config files. I'd not considered the certificates as I only place them there to make the path consistent in the example psd1 files!

I guess they might have been replaced or additional certificates added? Have you replaced them or added new Cerys here? If this is something that should be added, feel free to submit a PR :P

**Comment by csandfeld** [comment]
Haven't replaced certs or added additional myself, but just thought it might make sense to include that as well. Didn't realize you had already made the Import/Export functions.

**Comment by iainbrighton** [comment]
@csandfeld No problem. I'll leave this open until you've had a chance to look over the code/try the functionality out?
