### ISSUE TITLE
Add Guest Integration Services support

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lability#69]
Now that the Guest Integration Services support is enabled in the bundled xHyper-V DSC resource, it would be good to expose this as an option.

Question is: Should this be __ON__ by default?

**Comment by MS-MatthewWalker** [comment]
Given it adds the capability to use the Copy-VMFile cmdlet to copy files into a VM  - I would say Yes

**Comment by iainbrighton** [comment]
@MS-MatthewWalker I think I'll add it, but won't set it to __ON__ by default. This mimics the default behaviour and you can always enable it by default with `Set-LabVMDefault` if wanted.
