### ISSUE TITLE
Start-LabConfiguration -Path throws error if not found even when -Force is included

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#98]
Although -Force isn't implemented for this I would expect that if the Path for the Configurations didnt exist then it would create them.

Example error message as below

![labilityerror4](https://cloud.githubusercontent.com/assets/6355225/14547974/b969b59c-02aa-11e6-8a7d-e8b055ae0445.PNG)

**Comment by iainbrighton** [comment]
Even if it created that path, the configuration would fail as there would be no .MOF files (although with a different error message). The -Force parameter is for overwriting existing VMs:
```
[1] C:\> help Start-LabConfiguration -Parameter Force

-Force [<SwitchParameter>]
    Specifies that any existing virtual machine with a matching name, will be removed and recreated. By
    default, if a virtual machine already exists with the same name, the cmdlet will generate an error.

    NOTE: If the -Force parameter is specified - and a virtual machine with the same name already exists -
    ALL EXISTING DATA WITHIN THE VM WILL BE LOST.

    Required?                    false
    Position?                    named
    Default value                False
    Accept pipeline input?       true (ByPropertyName)
    Accept wildcard characters?  false
```
If you specified the `-SkipMofCheck` parameter then this error should not show itself?

**Comment by kilasuit** [comment]
Yeah - this was my bad
Closing this off
