### ISSUE TITLE
Add support for custom disk sizing & additional disks

### ISSUE THREAD

**Issue by kilasuit** [VirtualEngine/Lability#99]
Depending on the Lab scenario there can be a requirement to have a smaller C Drive and then push items like logs or data onto other drives.

So within this it would make sense to be able to replicate this in a similar fashion within Lability

Adding Additional Drives with naming convention, type, size & drive letter shouldn't be too much additional work but adding the flexibility for the main Drive likely will be.

**Comment by iainbrighton** [comment]
I think being able to specify disk sizes is a great addition. I'll check to make sure the xVhd resource supports this (I'm pretty sure it does).

However, as we're relying on the xVMHyperV DSC resource under the hood, this will need to support multiple VHDs first. This is primarily why I decided to use the DSC resources to begin with - any support added to the DSC resources can be used by Lability (double win!).

**Comment by PlagueHO** [comment]
As I'm a bit of a Lability convert, I'd be glad to help out where I can.

I have a few labs that I currently build out that contain SQL Servers (with multiple log/data disks) or storage spaces with multiple disks. So ideally I'd like to be able to do this with Lability too.

I could look at extending the xHyper-V DSC resources to enable some of these features if it would help? But first I'd probably look at sorting the tech debt on xHyper-V it and bringing it up to HQRM. Now that AppVeyor VMs can be rebooted mid run it should be possible to create integration tests for xHyper-V.

Just let me know what might be helpful.

**Comment by iainbrighton** [comment]
@PlagueHO Yeah - I think that getting the xHyper-V module up to HQRM standards should be the priority. Lability can then leverage this functionality and everyone's a winner! It would also be an opportunity to split the xVMHyperV resource into separate VM, network and disk resources as discussed [here](https://github.com/PowerShell/xHyper-V/issues/47). That resource is simply doing too much and could be easily replaced with a composite resource.

**Comment by PlagueHO** [comment]
I've [submitted a PR](https://github.com/PowerShell/xHyper-V/pull/65) to xHyper-V to add HQRM support for creating DVD Drives (and mounting ISO's to them). This should be easy enough to clone and modify to support adding/removing VM Hard Disk drives.

I've included integration tests as well, but these won't work on AppVeyor because unfortunately the AppVeyor machines don't expose VT-x - so Hyper-V won't install.

HTH

**Comment by iainbrighton** [comment]
Implemented in #285
